### ISSUE TITLE
Omnisharp on vscode is slow with large solution

### ISSUE THREAD

**Issue by damageboy** [OmniSharp/omnisharp-roslyn#1074] opened 2017-12-22 12:19 UTC
I have a rather large solution (around 80 projects) in the .sln.

I notice that omnisharp is loading the solution one project at a time.

Here's a sample screenshot of the entire process tree:

![image](https://user-images.githubusercontent.com/125730/34297810-fae8a060-e722-11e7-96ff-c0cadccbeaf3.png)

This is of course quite unfortunate since I do have 4 cores that are more than free to participate in loading this whole mess much faster on other IDEs like VS/Rider.

Is there any plan to improve omnisharp in this respect?

A quick search in the open issues didn't show anything...

**Comment by david-driscoll** [comment] 2018-01-09 23:41
Definitely something we're looking at I believe @DustinCampbell had some stuff in the works (probably in his head...)

**Comment by DustinCampbell** [comment] 2018-01-17 16:35
This is a duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/926.

**Closed by DustinCampbell** 2018-01-17 16:35 UTC
Labels: duplicate
