### ISSUE TITLE
[need help] why do I got duplicate lint suggestions in VS Code

### ISSUE THREAD

**Issue by imba-tjd** [OmniSharp/omnisharp-roslyn#1093] opened 2018-01-23 12:55 UTC
* OS Version: WIndows 10 1709
* VS Code Version: 1.19.2
* C# extension Version: 1.13.1

I have gotten this problem a few month before. I have tried to disabled all other extension or reinstall this extension and VS Code.
This Project was created by`dotnet new console`. tasks.json and launch.json were also automatically created.
What can I do?
![image](https://user-images.githubusercontent.com/24759802/35276325-02282f3e-007e-11e8-8a6d-23d0471a8471.png)

**Comment by DustinCampbell** [comment] 2018-01-23 17:13
Hi! This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1965.

**Closed by DustinCampbell** 2018-01-23 17:13 UTC
Labels: duplicate
