### ISSUE TITLE
"excludeSearchPatterns" not honored

### ISSUE THREAD

**Issue by Iron-E** [OmniSharp/omnisharp-roslyn#1766] opened 2020-04-14 03:48 UTC
# Problem

No matter what files are included or excluded inside of the "omnisharp.json" file, the OmniSharp-Roslyn server seems to ignore the settings and scan everything anyway. This is observed on both Neovim and VSCode.

# Steps to Reproduce

1. Create an "omnisharp.json" file (in the proper directory, such as "~/.omnisharp/omnisharp.json" on linux) and fill it with the following:
	```json
	{
		"fileOptions": {
			"systemExcludeSearchPatterns": [
				"**/node_modules/**/*",
				"**/bin/**/*",
				"**/obj/**/*",
				"/tmp/**/*"
			],
			"excludeSearchPatterns": [
				"**/node_modules/**/*",
				"**/bin/**/*",
				"**/obj/**/*",
				"/tmp/**/*"
			]
		}
	}
	```
2. Build any code with `dotnet build`.
3. Check for errors with the editor of your choice. You will see errors such as this:
	```quickfix
	Project/obj/Debug/netcoreapp3.1/File.AssemblyInfo.cs|11 col 1 warning| Unnecessary using directive.
	```
	* Notice the directory matches the pattern `**/obj/**/*`, yet it has still been scanned for issues and the issues have been reported.

**Comment by filipw** [comment] 2020-04-14 04:41
as documented here https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options, this is not how the feature works 

> Warning: this features allows disabling of project file / solution file discovery not individual .cs files.

**Comment by filipw** [comment] 2020-04-14 04:44
duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1460

**Closed by filipw** 2020-04-14 04:44 UTC
