### ISSUE TITLE
Omnisharp does not find Unity3D assemblies

### ISSUE THREAD

**Issue by HiPhish** [OmniSharp/omnisharp-roslyn#1948] opened 2020-09-17 16:59 UTC
Hello,

I am trying to get Omnisharp to work with a Unity3D project on GNU/Linux (Kubuntu 20.04). My editor is Neovim 0.5 (pre-release) which includes its own LSP client. Neovim downloaded the latest Omnisharp release (1.37.1). The server is working, I am getting diagnostic messages, documentation and code completion, but it acts as if it does not know anything about Unity.

- `mono --version` shows 6.8.0.105 for the globally installed Mono
- The launch command used by Neovim is `~/.cache/nvim/nvim_lsp/omnisharp/run --languageserver --hostPID <PID of Neovim process>`

I would assume that Omnisharp uses its bundled Mono. How can I get Omnisharp to produce log files, and where can I find them?

![Screenshot_20200917_183504](https://user-images.githubusercontent.com/4954650/93503077-e2089a00-f917-11ea-963d-c09f4cdd4315.png)

**Comment by snowgoon88** [comment] 2020-09-17 17:46
My ultimate goal is nearly the same : use emacs+lsp on Unity files. (see #1947)
I got some debug by *manually* running omnisharp with `./run -s <project_root_path> -v > logfile` (and then killing the server process once messages where logged in the file). Not sure it is the best way.

**Comment by R0flcopt3r** [comment] 2020-09-18 13:31
Go to `/usr/lib/mono` and check what the latest version you have, then set `FrameworkPathOverride` to point to that folder.

For me it's worked setting it to both `/usr/lib/mono/4.5` and `/usr/lib/mono/4.8-api`.

```
export FrameworkPathOverride=/lib/mono/4.5
```

**Comment by snowgoon88** [comment] 2020-09-18 15:52
I have not yet tried this solution (and I will) but..
I did manage to get it working on Emacs by modifying the `run` script in omnisharp-roselyn to take into account the globally installed `mono` if present and if the version is high enough.

Everything is here : https://github.com/emacs-lsp/lsp-mode/issues/2188#issuecomment-694945601

**Comment by ericdallo** [comment] 2020-09-20 17:28
I have the same issue as @snowgoon88, and agree with the `run` script change of @snowgoon88.
Also, is that script [specific for windows only](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/mono-packaging/run#L9)?

**Comment by ericdallo** [comment] 2020-09-21 01:18
I have the issue with emacs `lsp-mode`, @razzmatazz do you know what could it be?

**Comment by razzmatazz** [comment] 2020-09-21 06:46
> I have the issue with emacs `lsp-mode`, @razzmatazz do you know what could it be?

I am afraid I have no experience with Unity. My question is, does vscode do it better, and if they do (and they are by far the most popular client for omnisharp-roslyn IMHO) -- then we can replicate the solutions by looking at the workarounds/framework/mono discovery code they do.

**Comment by filipw** [comment] 2020-09-21 07:07
When OmniSharp starts on its own embedded Mono it will have no reference assemblies for desktop ..NET and Unity and other non-.NET Core development won't work or be limited.

In VS Code there is a setting to start OmniSharp on global Mono instead and that allows full compatibility with all desktop .NET development. I would imagine in this case a setting like this is needed too.

However, I don't think this is an issue for OmniSharp itself as it already provides the necessary tools for achieving this - it's just the client must make the decisions, therefore I would recommend to move this issue to the client implementation(s).

**Comment by nickspoons** [comment] 2020-09-21 07:17
How does VSCode do this, @filipw? Is it a command line flag passed to the server? Or are you referring to omnisharp.json settings?

**Comment by snowgoon88** [comment] 2020-09-21 07:58
On VS code (Linux), I tried playing with setting ALWAYS use global mono and setting the path to the global mono (it is done via a .json file) and then restart the server **several times** (with the command palette of VS code). But it does not work : Unity referenced functions/classes are not recognized.

With Emacs (Linux, and my `run` file), it works in two steps : open the .cs file -> server started once with global mono. Then, I restart the server from Emacs (using lsp-mode) and it work.

So, I guess the issus is client depend, sadly...

**Comment by filipw** [comment] 2020-09-21 08:40
@nickspoons there is a setting `omnisharp.useGlobalMono` which can be set to `always`. It then uses global Mono form the PATH to start OmniSharp.exe process. Additionally a custom path can be provided too. https://github.com/OmniSharp/omnisharp-vscode/blob/97768562a4f950db687d5d9314da4a854c9e6f4c/src/omnisharp/launcher.ts#L264-L277

@snowgoon88 if you have trouble with VS Code, please open an issue in https://github.com/OmniSharp/omnisharp-vscode and provide your OmniSharp log with `omnisharp.logginglevel: "debug"` enabled.

**Comment by ericdallo** [comment] 2020-09-21 12:35
Thanks for the help everybody, I tested with emacs and vscode using the `useGlobalMono` and pointing to mono6 path, but it didn't work too, but I think it's my OS's fault. I use NixOS, and my mono global installation does not have msbuild updated.

**Comment by filipw** [comment] 2020-09-21 12:54
ah that could be - not every mono distro has MSBuild bundled

**Comment by ericdallo** [comment] 2020-09-21 14:01
FTR this issue is related: https://github.com/NixOS/nixpkgs/issues/95911

**Comment by HiPhish** [comment] 2020-09-21 17:23
Thank you everyone for your input. To summarize, the issue is that the bundled Mono cannot find any 3rd party assemblies at all. It is the responsibility of the client to start the server with a global Mono installation. I have for now modified the `run` script to change one variable:

```sh
bin_dir=/usr/bin  # Previous value: ${base_dir}/bin
```
That way when the `run` script starts the server (`"${mono_cmd}" "${omnisharp_cmd}" "$@"`) it will use `usr/bin/mono` as the Mono binary.

Now the next question is how to tell the server which Mono to use. From looking at the `run` script there does not appear to be any way of passing a command-line option or environment variable to the script. So I figure the best course of action would be to forego the `run` script altogether and just invoke `mono` and `omnisharp` directly. From the looks of it the script does not really do much anyway.

Is this the correct way? From what I can understand the VS Code plugin does the same. Please correct me if I'm wrong, I don't actually know TypeScript, so I'm just taking an educated step.

![Screenshot_20200921_190746](https://user-images.githubusercontent.com/4954650/93799735-d8e13b00-fc3f-11ea-976e-acb156c5cbb6.png)

**Comment by ericdallo** [comment] 2020-09-22 02:06
For NixOS users I fixed with this: https://github.com/NixOS/nixpkgs/pull/98435, basically, the `msbuild` inside the omnisharp does not work for unity, that's why using a global mono works for everybody.

**Comment by filipw** [comment] 2021-01-22 14:18
I will close this because at the end, this is by design - OmniSharp doesn't ship with reference assemblies for .NET Framework. we will add a better error message in https://github.com/OmniSharp/omnisharp-roslyn/issues/2029 so that it's clear that full Mono is needed when reference assemblies are not found

**Closed by filipw** 2021-01-22 14:18 UTC
Labels: mono, unity

**Comment by axelson** [comment] 2021-01-27 19:59
> @nickspoons there is a setting `omnisharp.useGlobalMono` which can be set to `always`. It then uses global Mono form the PATH to start OmniSharp.exe process. Additionally a custom path can be provided too. https://github.com/OmniSharp/omnisharp-vscode/blob/97768562a4f950db687d5d9314da4a854c9e6f4c/src/omnisharp/launcher.ts#L264-L277

Is that setting part of the configuration for omnisharp-roslyn? I don't see it documented on the configuration page: https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options

Or is it VSCode specific or something else?

**Comment by nickspoons** [comment] 2021-01-27 20:28
@axelson That's a VSCode setting, regarding how the OmniSharp-roslyn process is started.

**Comment by HiPhish** [comment] 2021-01-28 21:34
Is there a way of setting this option outside of VSCode as well? Like a command-line parameter, environment variable or configuration file?

**Comment by sp1n0r** [comment] 2021-02-01 16:54
Hi I'm on Windows using nvim lspconfig omnisharp language server. It doesn't recognize the assemblies as well. When loading a basic script it says that it couldn't find monobehavior class

**Comment by Mathijs-Bakker** [comment] 2021-02-03 23:02
@HiPhish Thanks!

Mono binaries on latest MacOS's are installed elsewhere..
Thought I post it here as it could be of any help for others.
```bash
bin_dir=/Library/Frameworks/Mono.framework/Versions/Current/bin
```
<img width="775" alt="Schermafbeelding 2021-02-03 om 23 47 35" src="https://user-images.githubusercontent.com/7645831/106819788-95312000-667a-11eb-99fd-daa329a73ec4.png">

**Note:** Unity doesn't generate _.sln_ and _.csproj_ files. So for _(Neo)Vim_ you have to create them yourself, in case of new projects. Or open a _.cs_ file in VS or Rider and let them auto generate it for you.

**Comment by morabitom** [comment] 2022-01-09 23:17
@harrisonmg I had better luck by avoiding the run script entirely, I tried to mess with it quite a bit like you did. Here is the way I setup the server with nvim, instead of calling the run script I call omnisharp using global mono directly.

```
locallspconfig = require "lspconfig"
local pid = vim.fn.getpid()
local omnisharp_bin = "/home/mark/.local/share/nvim/lsp_servers/omnisharp/omnisharp/omnisharp/OmniSharp.exe" 

return {
    cmd = { "mono", omnisharp_bin, "--languageserver","--hostPID", tostring(pid) },
    filetypes = { "cs", "vb" },
    init_options = {},
    on_new_config = function(new_config, new_root_dir)
          if new_root_dir then
            table.insert(new_config.cmd, '-s')
            table.insert(new_config.cmd, new_root_dir)
          end
        end,
    root_dir = lspconfig.util.root_pattern("*.sln");
}
```

**Comment by willparsons** [comment] 2022-01-23 21:41
I still get the same issue that MonoBehaviour and other Unity types cannot be found. Even with the fix that @HiPhish gave.

**Comment by nyngwang** [comment] 2022-02-14 06:44
@morabitom I got this error: `Client 1 quit with exit code 2 and signal 0`

**Comment by nyngwang** [comment] 2022-02-14 07:56
@HiPhish @Mathijs-Bakker With dotnet-6.0 since there is no script file `run`, all the solutions on this thread didn't work for me :(

**Comment by filipw** [comment] 2022-02-14 10:27
.NET 6.0 build does not support Unity.

**Comment by nyngwang** [comment] 2022-02-14 11:16
> .NET 6.0 build of OmniSharp does not support Unity.

Wow, so which version should I use?

**Comment by nyngwang** [comment] 2022-02-14 21:24
> @harrisonmg I had better luck by avoiding the run script entirely, I tried to mess with it quite a bit like you did. Here is the way I setup the server with nvim, instead of calling the run script I call omnisharp using global mono directly.
> 
> ```
> locallspconfig = require "lspconfig"
> local pid = vim.fn.getpid()
> local omnisharp_bin = "/home/mark/.local/share/nvim/lsp_servers/omnisharp/omnisharp/omnisharp/OmniSharp.exe" 
> 
> return {
>     cmd = { "mono", omnisharp_bin, "--languageserver","--hostPID", tostring(pid) },
>     filetypes = { "cs", "vb" },
>     init_options = {},
>     on_new_config = function(new_config, new_root_dir)
>           if new_root_dir then
>             table.insert(new_config.cmd, '-s')
>             table.insert(new_config.cmd, new_root_dir)
>           end
>         end,
>     root_dir = lspconfig.util.root_pattern("*.sln");
> }
> ```

@morabitom Thank you so much! This works! I'm on the newest version v1.38.0.

**Comment by harrisonmg** [comment] 2022-05-15 08:31
> @harrisonmg I had better luck by avoiding the run script entirely, I tried to mess with it quite a bit like you did. Here is the way I setup the server with nvim, instead of calling the run script I call omnisharp using global mono directly.
> 
> ```
> locallspconfig = require "lspconfig"
> local pid = vim.fn.getpid()
> local omnisharp_bin = "/home/mark/.local/share/nvim/lsp_servers/omnisharp/omnisharp/omnisharp/OmniSharp.exe" 
> 
> return {
>     cmd = { "mono", omnisharp_bin, "--languageserver","--hostPID", tostring(pid) },
>     filetypes = { "cs", "vb" },
>     init_options = {},
>     on_new_config = function(new_config, new_root_dir)
>           if new_root_dir then
>             table.insert(new_config.cmd, '-s')
>             table.insert(new_config.cmd, new_root_dir)
>           end
>         end,
>     root_dir = lspconfig.util.root_pattern("*.sln");
> }
> ```

Thanks, but no dice. I don't know what else I could be doing wrong. I'm using the Mono build of OmniSharp mentioned by @nyngwang and mono 6.8.0.105 (though 6.12.0.147 also didn't work).

I still get a load of
```
"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OmniSharp.Extensions.JsonRpc.Client.OutgoingNotification | @Request='OmniSharp.Extensions.JsonRpc.Client.OutgoingNotification'"
```
messages until the server eventually initializes after an unacceptably long few minutes (perhaps because of all the `type or namespace not found` errors?)

This is driving me nuts.

**Comment by nyngwang** [comment] 2022-05-15 09:23
@harrisonmg Which mono exactly did you install on your computer? Have a long time no writing C# but I might also check it later.

**Comment by harrisonmg** [comment] 2022-05-15 15:14
Currently I have installed mono version 6.12.0.122 using [these instructions](https://www.mono-project.com/download/stable/#download-lin) and doing `sudo apt install mono-complete`.

Thanks for your help!

**Comment by apyra** [comment] 2025-04-22 13:09
The Ultimate, multiplatform solution, Use Neovim as Code Editor for unity [nvim-unity](https://github.com/apyra/nvim-unity.git) , sync the project files automaticaly: [nvim-unity-sync](https://github.com/apyra/nvim-unity-sync.git), Great workflow!
