### ISSUE TITLE
False error reportings 

### ISSUE THREAD

**Issue by curtisd7** [OmniSharp/omnisharp-roslyn#2007] opened 2020-11-07 23:52 UTC
This is an error that has been happening for a while whenever i write code then deleted it errors show up like the code is still there but it's deleted whenever close and reopen vscode it fixes it but that's really annoying to do often for ex: 
![image](https://user-images.githubusercontent.com/44918079/98453727-0ddb1b80-2122-11eb-8540-93ec80270e6b.png)

**Comment by filipw** [comment] 2020-11-16 07:54
this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4192#issuecomment-725598099
I will close this because it is not a problem of Omnisharp server, but of the VS Code extension

**Closed by filipw** 2020-11-16 07:54 UTC
