### ISSUE TITLE
VSCode Omnisharp fails to initialize: System.MissingMethodException

### ISSUE THREAD

**Issue by pheuter** [OmniSharp/omnisharp-roslyn#1492] opened 2019-05-13 18:19 UTC
OmniSharp Output Log:

```
Starting OmniSharp server at 5/13/2019, 2:16:09 PM
    Target: /Users/mark/src/CareSwitch/CareSwitch.sln

OmniSharp server started.
    Path: /Users/mark/.vscode/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/run
    PID: 28855

System.MissingMethodException: Method not found: int System.Collections.HashHelpers.GetMinPrime()
  at System.Collections.Generic.HashSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00007] in <45733548a32d4c5eb058df83dba0f33a>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite (System.Type serviceType, System.Type implementationType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) [0x0011b] in <824e19d8b53a48d8867d85feb58265d3>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact (Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor, System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) [0x00061] in <824e19d8b53a48d8867d85feb58265d3>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) [0x00018] in <824e19d8b53a48d8867d85feb58265d3>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) [0x0002e] in <824e19d8b53a48d8867d85feb58265d3>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor (System.Type serviceType) [0x0000c] in <824e19d8b53a48d8867d85feb58265d3>:0 
  at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) [0x00034] in <b4d1a66727f44ba888b54966284fabb4>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope) [0x00013] in <824e19d8b53a48d8867d85feb58265d3>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType) [0x00008] in <824e19d8b53a48d8867d85feb58265d3>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) [0x00000] in <824e19d8b53a48d8867d85feb58265d3>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService (System.IServiceProvider provider, System.Type serviceType) [0x00034] in <4b47b422bc4c4615bbdebe1df9b21b0d>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T] (System.IServiceProvider provider) [0x0000e] in <4b47b422bc4c4615bbdebe1df9b21b0d>:0 
  at OmniSharp.Stdio.Driver.Program+<>c__DisplayClass0_1.<Main>b__1 () [0x000f1] in <d50e1cd15b6f44e4a3353cf480263c72>:0 
  at OmniSharp.CommandLineApplication+<>c__DisplayClass11_0.<OnExecute>b__0 () [0x0000b] in <e207cb3ceaae4aab812ba001608b89a7>:0 
  at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute (System.String[] args) [0x00039] in <344a1e8cd6594b17b1e01f8df6ae8827>:0 
  at OmniSharp.CommandLineApplication.Execute (System.Collections.Generic.IEnumerable`1[T] args) [0x00042] in <e207cb3ceaae4aab812ba001608b89a7>:0 
  at OmniSharp.Stdio.Driver.Program+<>c__DisplayClass0_0.<Main>b__0 () [0x00028] in <d50e1cd15b6f44e4a3353cf480263c72>:0 
  at OmniSharp.HostHelpers.Start (System.Func`1[TResult] action) [0x0001c] in <e207cb3ceaae4aab812ba001608b89a7>:0 
```

I've tried setting custom versions for `omnisharp.path` as well as installing my own global version of mono, but the same error keeps popping up.

**Comment by filipw** [comment] 2019-06-04 06:39
which version of Mono do you have installed on your machine? My initial guess is that it's an old version of Mono that is causing this
Try installing latest mono from https://www.mono-project.com/download/stable/

**Comment by pheuter** [comment] 2019-06-04 15:40
I have tried and it didn't seem to fix the issue.

**Comment by filipw** [comment] 2019-06-04 15:43
could you please post the full OmniSharp log?

**Comment by pheuter** [comment] 2019-06-06 12:52
unfortunately i don't have access to that computer right now, but i will try and get the full logs next time i get the chance. i do remember explicitly installing the latest version of mono globally and the logs picking up on that version number.

**Comment by MingStar** [comment] 2020-09-02 08:03
+1 
I have the exact same error message.

OmniSharp server started.
    Path: /Users/weiming/.vscode/extensions/ms-dotnettools.csharp-1.23.1/.omnisharp/1.37.0/run
    PID: 1466

System.MissingMethodException: Method not found: int System.Collections.HashHelpers.GetMinPrime()


my Mono version is 6.10.0.104

**Comment by MingStar** [comment] 2020-09-02 11:20
OK, my issue is indeed related to an old version of Mono installed (via Homebrew on MacOS).

After I do:

> $ brew uninstall mono

The issue is gone!

**Comment by filipw** [comment] 2020-11-26 14:49
This is known to have been caused by an old Mono. Closing - thanks!

**Closed by filipw** 2020-11-26 14:49 UTC
Labels: needs more info
