### ISSUE TITLE
Integration with nvim-lsp

### ISSUE THREAD

**Issue by svermeulen** [OmniSharp/omnisharp-roslyn#1777] opened 2020-04-29 04:49 UTC
It sounds like this project can be run as an LSP server.  Has anyone been able to get this working with [neovim's built-in support for LSP](https://github.com/neovim/nvim-lsp)?

**Comment by razzmatazz** [comment] 2020-05-17 17:57
I believe #1791 was the main blocker for the issue of LSP server not working with many clients. Maybe the next release with this PR merged will fix it for you.

**Comment by filipw** [comment] 2020-05-25 14:42
can you try again after the latest release?

**Comment by filipw** [comment] 2020-06-26 20:09
I will close this aa resolved, feel free to provide more info in case you still have any issuew

**Closed** 2020-06-26 20:09 UTC
Labels: lsp

**Comment by adelarsq** [comment] 2020-06-26 20:20
@filipw Thanks for notice. I can confirm that it's working with nvim-lsp. I'm already using but still didn't have time to send a pull request on the plugin repository. I will send on next week I think.

**Comment by Iron-E** [comment] 2020-06-28 02:40
> @filipw Thanks for notice. I can confirm that it's working with nvim-lsp. I'm already using but still didn't have time to send a pull request on the plugin repository. I will send on next week I think.

How did you get it working? I just left a comment [here](https://github.com/OmniSharp/omnisharp-roslyn/issues/1191#issuecomment-650672850) because I had an issue getting the client and server to stay connected.

**Comment by adelarsq** [comment] 2020-06-28 18:05
@Iron-E The problem is on `root_dir` config, that don't generate de right path, so the `omnisharp` never starts.

On the documentation says that the config are similar to coc.nvim, but I find that isn't really like that for root directory patterns.

**Comment by adelarsq** [comment] 2020-06-28 18:18
@Iron-E The problem is on root_dir config, that don't generate de right path, so the omnisharp never starts.

On the documentation says that the config are similar to coc.nvim, but I find that isn't really like that for root directory patterns.

**Comment by svermeulen** [comment] 2020-06-28 18:53
@adelarsq Can you update this issue when you add a PR to nvim-lsp?

**Comment by adelarsq** [comment] 2020-06-28 19:47
Yes, I can. I will take note to remember.

**Comment by adelarsq** [comment] 2020-07-06 16:57
@svermeulen Someone else has sended a PR for omnisharp https://github.com/neovim/nvim-lsp/pull/291 (almost the same that I was preparing). We are investigating some issues about the diagnostics on there.

I also did send a PR to solve a issue with C#/F# language servers https://github.com/neovim/nvim-lsp/pull/296, so we can use file patterns to detect the root directory (like `*.sln` for all files ended with `sln`). I'm already using for both C# and F#. Just waiting the merge to be approved.

**Comment by svermeulen** [comment] 2020-07-06 18:02
Thanks!

**Comment by svermeulen** [comment] 2020-07-13 03:34
BTW I am not an expert on this repo but after poking around in the code I made [this change](https://github.com/svermeulen/omnisharp-roslyn-1/commit/16967699f16153aaa5db2bd43988210a85bc9f58) in my local build, in order to fix the issues with diagnostics not showing up when using neovim and nvim-lsp.  I'm not sure if it actually makes sense or not, so I'm reluctant to make a PR, but posting here in case it's helpful

**Comment by Iron-E** [comment] 2020-07-13 18:05
I would go ahead and create the PR since it seems that others can confirm the fix as well. Mind pinging us here again when it's up?

**Comment by svermeulen** [comment] 2020-07-21 22:20
After learning more about it, I am now more convinced that the change I link to above is a really bad idea.

In my case, it looks like the problem is caused by the "file open" event being triggered to omnisharp server before omnisharp server has fully loaded all the projects in the solution.  This is why, if you go to a different file, diagnostics do work.  They just don't work in the initial set of files that were opened before the omnisharp server has fully initialized
