### ISSUE TITLE
Cannot load projects that use an MSBuild SDK package

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-roslyn#1190] opened 2018-05-16 09:11 UTC
MSBuild 15.6 added a new SDK resolver that can use NuGet packages as SDKs.  When opening a project that uses a NuGet-based SDK package, OmniSharp cannot load the project.

**Repro**
git clone https://github.com/dotnet/arcade
Open VS Code

**Expected**
OmniSharp uses the same SDK resolution that VS 15.6 and the .NET Core CLI 2.1.105 use.

**Actual**
Project fails to load with:
```
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/namc/dev/dotnet/arcade/src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj'.
/Users/namc/dev/dotnet/arcade/src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'RoslynTools.RepoToolset' specified could not be found.  /Users/namc/dev/dotnet/arcade/src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj
  at Microsoft.Build.Evaluation.ProjectCollection.LoadProject (System.String fileName, System.String toolsVersion) [0x00000] in <61115f75067146fab35b10183e6ee379>:0 
  at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore (System.String filePath) [0x0003e] in <64f2a38974d54ecaaa93e3697628b738>:0 
  at OmniSharp.MSBuild.ProjectLoader.BuildProject (System.String filePath) [0x0000d] in <64f2a38974d54ecaaa93e3697628b738>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load (System.String filePath, OmniSharp.MSBuild.ProjectLoader loader) [0x00014] in <64f2a38974d54ecaaa93e3697628b738>:0 
  at OmniSharp.MSBuild.ProjectManager+<>c__DisplayClass23_0.<LoadProject>b__0 () [0x00000] in <64f2a38974d54ecaaa93e3697628b738>:0 
  at (wrapper delegate-invoke) System.Func`1[System.ValueTuple`2[OmniSharp.MSBuild.ProjectFile.ProjectFileInfo,System.Collections.Immutable.ImmutableArray`1[OmniSharp.MSBuild.Logging.MSBuildDiagnostic]]].invoke_TResult()
  at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject (System.String projectFilePath, System.Func`1[TResult] loadFunc) [0x0001b] in <64f2a38974d54ecaaa93e3697628b738>:0 
```
**Details**
 
See https://github.com/microsoft/msbuildsdks and https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk#how-project-sdks-are-resolved for more details

VS Code C# extension: 1.15.2
VS Code: 1.23.1

**Comment by DustinCampbell** [comment] 2018-05-16 18:01
@natemcmaster : Is this a duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1138?

**Comment by DustinCampbell** [comment] 2018-05-16 18:14
Yeah, I don't know if the distinction is important either. There has been no work on OmniSharp done to support MSBuild SDKs to date.

**Comment by DustinCampbell** [comment] 2018-05-16 18:15
Would you be willing to provide your full OmniSharp Log instead of just the error?

**Comment by DustinCampbell** [comment] 2018-05-16 19:42
FYI that I have a good idea what's causing this. Mono 5.12.0 does ship the SDK resolver for acquiring MSBuild SDKs from NuGet. However, OmniSharp is setting the `MSBuildSdksPath` environment variable directly, which overrides the SDK resolvers.

**Comment by DustinCampbell** [comment] 2018-05-16 19:47
Yup. I was able to prototype a change to OmniSharp that would allow it to properly use MSBuild SDKs when a Mono is installed SxS that supports them. I'll try to work that into a proper fix in the next day or two.

**Closed** 2018-05-21 19:20 UTC
Labels: fixed, msbuild

**Comment by DustinCampbell** [comment] 2018-05-21 19:52
It looks like the build is ready, so you should be able to give that option a spin.

**Comment by natemcmaster** [comment] 2018-05-23 00:27
Thanks! I gave it a spin and it fixes the error I was seeing. I'm seeing a new issues now, but I'll open a new bug as that appears to be unrelated.
