### ISSUE TITLE
OmniSharp restarts on autocomplete

### ISSUE THREAD

**Issue by anfomin** [OmniSharp/omnisharp-roslyn#618] opened 2016-08-12 08:28 UTC
I'm using VS code 1.4.0. OmniSharp was working normally until today. When I'm trying to open autocomplete window in specific project OmniSharp restarts infinitely:

Here is output:

```
[INFO] Starting OmniSharp at '/Users/afomin/Developer/Rent'...
[INFO] Started OmniSharp from '/Users/afomin/.vscode/extensions/ms-vscode.csharp-1.3.0/out/.omnisharp-coreclr/OmniSharp' with process id 11615...
OmniSharp: -s /Users/afomin/Developer/Rent --hostPID 11585 DotNet:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/Users/afomin/Developer/Rent' on host 11585.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/afomin/Developer/Rent
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /Users/afomin/Developer/Rent/src/Rent.ClientSite
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/src/Rent.ClientSite/project.json => 4a21c53c-952d-4bf3-8bc6-29d4350ddd00
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /Users/afomin/Developer/Rent/src/Rent.Common
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/src/Rent.Common/project.json => 4d087ce0-65b1-43b7-94de-d50aacd13620
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/src/Rent.Common/project.json => ecb448bb-e936-43ea-8ba7-d25f4b1bf6e6
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /Users/afomin/Developer/Rent/src/Rent.Models
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/src/Rent.Models/project.json => 27513f22-65b5-4fb4-9669-75e9093582bd
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/src/Rent.Models/project.json => dc26a4ea-661c-4239-969b-ad6b53323b33
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /Users/afomin/Developer/Rent/src/Rent.JobFiles
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/src/Rent.JobFiles/project.json => c62c4573-6ac4-4382-843d-ff319c023afe
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /Users/afomin/Developer/Rent/src/Rent.Portal
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/src/Rent.Portal/project.json => af2035e3-6509-45b9-a285-5b192ab89af7
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /Users/afomin/Developer/Rent/src/Rent.Promo
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/src/Rent.Promo/project.json => a8ab0b1c-9008-4267-b977-ea8f6ba96c41
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /Users/afomin/Developer/Rent/test/Rent.Portal.Test
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/test/Rent.Portal.Test/project.json => 707b654d-c44d-4196-8677-951b255c1cbd
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /Users/afomin/Developer/Rent/test/Rent.Test
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/afomin/Developer/Rent/test/Rent.Test/project.json => 60dff26b-2c24-436d-8282-c9ee4cfd0516
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.ClientSite/.NETCoreApp,Version=v1.0
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 165 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 2 and removed 0 project references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 21 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.Common/.NETFramework,Version=v4.6
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 116 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 1 and removed 0 project references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 46 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.Common/.NETStandard,Version=v1.6
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 141 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 1 and removed 0 project references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 46 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.Models/.NETFramework,Version=v4.6
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 69 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 48 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.Models/.NETStandard,Version=v1.5
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 90 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 48 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.JobFiles/.NETCoreApp,Version=v1.0
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 154 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 2 and removed 0 project references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 1 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.Portal/.NETCoreApp,Version=v1.0
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 165 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 2 and removed 0 project references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 80 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.Promo/.NETCoreApp,Version=v1.0
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 164 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 2 and removed 0 project references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 5 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.Portal.Test/.NETCoreApp,Version=v1.0
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 182 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 4 and removed 0 project references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 9 and removed 0 documents.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Rent.Test/.NETStandard,Version=v1.6
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 141 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 2 and removed 0 project references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 12 and removed 0 documents.
[INFORMATION:OmniSharp#MSBuild] Detecting projects in '/Users/afomin/Developer/Rent/Rent.sln'.
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'src\Rent.Common\Rent.Common.xproj'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'src\Rent.Models\Rent.Models.xproj'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'src'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'src\Rent.Portal\Rent.Portal.xproj'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'Solution Items'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'src\Rent.Promo\Rent.Promo.xproj'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'src\Rent.JobFiles\Rent.JobFiles.xproj'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'src\Rent.ClientSite\Rent.ClientSite.xproj'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'test'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'test\Rent.Portal.Test\Rent.Portal.Test.xproj'
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'test\Rent.Test\Rent.Test.xproj'
[INFORMATION:OmniSharp.Startup] Configuration finished.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 374ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 19ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 3ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 15ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 2ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 2ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 1ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 1ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 2ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 3ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 4ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 7ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 2ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 4ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 2ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 2ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 8ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 127ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 28ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 2ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 2ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 18ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 148ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 889ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 545ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 5ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 26ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 25ms
[INFORMATION:OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService] Applying Microsoft.CodeAnalysis.CodeFixes.FullyQualify.AbstractFullyQualifyCodeFixProvider+MyCodeAction
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/runcodeaction: 200 223ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 68ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 4ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 1ms
```

**Comment by tverboon** [comment] 2016-08-24 11:38
Same here, but it's only in a specific class that Omnisharp restarts when I invoke autocomplete. It restarts because of:

`[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.`

I found the problem in my class. It implements IDisposable. When I remove that it works like a charm again.

**Comment by anfomin** [comment] 2016-11-16 08:58
With the latest version 1.5.2 (VSCode) error still present:
```
[INFORMATION:OmniSharp.Startup] Configuration finished.
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 443ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 8ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 12ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 546ms
[INFORMATION:OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService] Applying Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1+OperationBasedCodeAction[Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax]
[INFORMATION:OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService] Applying Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider`1+OperationBasedCodeAction[Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax]
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /gotoDefinition: 500 1ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Specified argument was out of the range of valid values.
Parameter name: index
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 500 16ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Specified argument was out of the range of valid values.
Parameter name: index
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 500 1ms
```

**Comment by anfomin** [comment] 2016-11-22 17:15
Is there anybody alive? This bug prevents from using VS Code with C# because Omnisharp always restarts 👎

**Comment by willl** [comment] 2016-11-22 20:33
Would you happen to have a minimal code sample that reproduces this issue that you could share?

**Comment by edward93** [comment] 2016-12-03 20:55
I'm having this kind of issue too.

Here is my log:

```
Starting OmniSharp server at 12/4/2016, 12:49:12 AM
    Target: 

OmniSharp server started wth Mono
    Path: /Users/<Username>/.vscode/extensions/ms-vscode.csharp-1.6.0-beta3/bin/run
    PID: 19476

OmniSharp: -s /Users/<Username>/Workspace/<app> --hostPID 19434 --stdio DotNet:enablePackageRestore=false --encoding utf-8
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/<Username>/Workspace/<app>' on host 19434."},"Seq":1,"Type":"event"}
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/<Username>/Workspace/<App>
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /Users/<Username>/Workspace/<app>
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /Users/<Username>/Workspace/<app>/project.json => 518bfe3c-97d1-48bf-8abd-11e795ab805a
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] ProjectAI/.NETCoreApp,Version=v1.0
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 218 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 49 and removed 0 documents.
[INFORMATION:OmniSharp#MSBuild] No solution files found in '/Users/<Username>/Workspace/<app>'
[INFORMATION:OmniSharp.Startup] Configuration finished.
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 500 21ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 500 0ms
```

**Comment by filipw** [comment] 2016-12-05 08:37
Can you set `omnisharp. loggingLevel: “verbose”` in the user settings and gather output again? This should give more details about the error

**Comment by filipw** [comment] 2020-01-09 07:16
`DotNetProjectSystem` is no longer supported so I will close this issue.

**Closed by filipw** 2020-01-09 07:16 UTC
