### ISSUE TITLE
C# Plugin for VS Code not loading

### ISSUE THREAD

**Issue by Gore11** [OmniSharp/omnisharp-roslyn#1196] opened 2018-05-19 16:14 UTC
Hi i ried to use VS Code for Unity today and install also the C# extension but it is not working and i do not know why. I hope someone can help me...

VS Code v1.23.1

Dotnet is installed:
```
D:\Dokumente\Unity\Super Antonio Run\SuperAntonioRunApp>dotnet --info
.NET-Befehlszeilentools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

ERROR from Output console in VS Code:
```
Starting OmniSharp server at 19.5.2018, 18:07:02
    Target: d:\Dokumente\Unity\Super Antonio Run\Super Antonio Run.sln

OmniSharp server started
    Path: C:/Users/MarcGoritschnig/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/OmniSharp.exe
    PID: 16324

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei OmniSharp.MSBuild.Discovery.Providers.DevConsoleInstanceProvider.GetInstances()
   bei OmniSharp.MSBuild.Discovery.MSBuildLocator.GetInstances()
   bei OmniSharp.CompositionHostBuilder.RegisterMSBuildInstance(IMSBuildLocator msbuildLocator, ILogger logger)
   bei OmniSharp.CompositionHostBuilder.Build()
   bei OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IConfiguration configuration, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource)
   bei OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   bei Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   bei OmniSharp.HostHelpers.Start(Func`1 action)
```

**Comment by DustinCampbell** [comment] 2018-05-19 17:32
I suspect this is fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/1189. Try setting the `"omnisharp.path"` option in VS Code to `"latest"` to pick up the latest build, which should contain this fix.

**Comment by DustinCampbell** [comment] 2018-05-19 17:32
Duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1188.

**Comment by Gore11** [comment] 2018-05-19 17:57
Thanks "latest" as path is working.

**Closed** 2018-05-19 17:59 UTC
Labels: duplicate

**Comment by DustinCampbell** [comment] 2018-05-20 03:38
Fantastic! Thanks for verifying.
