### ISSUE TITLE
Support for IgnoredCodeIssues in config

### ISSUE THREAD

**Issue by FabioCZ** [OmniSharp/omnisharp-roslyn#301] opened 2015-09-17 16:04 UTC
Hey everyone,
I am trying to use a omnisharp.json config file with my project in VS Code (v0.8.0 atm). I'd like to be able to use `IgnoredCodeIssues` in my config. 

My omnisharp.json looks like this:

``` json
{    
"IgnoredCodeIssues": [
    "*Assuming assembly reference*"
    ],
}
```

However, Omnisharp fails to start and throws the following:

```
System.FormatException: Unsupported JSON token 'StartArray' was found. Path 'IgnoredCodeIssues', line 1 position 27.
  at Microsoft.Framework.ConfigurationModel.JsonConfigurationSource.Load (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.ConfigurationModel.JsonConfigurationSource.Load () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.ConfigurationModel.Configuration.Add (IConfigurationSource configurationSource) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.ConfigurationModel.JsonConfigurationExtension.AddJsonFile (IConfigurationSourceRoot configuration, System.String path, Boolean optional) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.ConfigurationModel.JsonConfigurationExtension.AddJsonFile (IConfigurationSourceRoot configuration, System.String path) [0x00000] in <filename unknown>:0 
  at OmniSharp.Startup..ctor () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
```

It'd be cool if this config option was supported

thanks

**Comment by david-driscoll** [comment] 2015-09-17 16:10
I think this is probably related to the fact that we're tied to to beta4
arm, and IConfiguration has had that feature added somewhat recently, this
is something that I think we can support in the future.
On Thu, Sep 17, 2015 at 12:04 PM Fabio Göttlicher <notifications@github.com>
wrote:

> Hey everyone,
> I am trying to use a omnisharp.json config file with my project in VS Code
> (v0.8.0 atm). I'd like to be able to use IgnoredCodeIssues in my config.
>
> My omnisharp.json looks like this:
>
> {    "IgnoredCodeIssues": [
>     "*Assuming assembly reference*"
>     ],
> }
>
> However, Omnisharp fails to start and throws the following:
>
> System.FormatException: Unsupported JSON token 'StartArray' was found. Path 'IgnoredCodeIssues', line 1 position 27.
>   at Microsoft.Framework.ConfigurationModel.JsonConfigurationSource.Load (System.IO.Stream stream) [0x00000] in <filename unknown>:0
>   at Microsoft.Framework.ConfigurationModel.JsonConfigurationSource.Load () [0x00000] in <filename unknown>:0
>   at Microsoft.Framework.ConfigurationModel.Configuration.Add (IConfigurationSource configurationSource) [0x00000] in <filename unknown>:0
>   at Microsoft.Framework.ConfigurationModel.JsonConfigurationExtension.AddJsonFile (IConfigurationSourceRoot configuration, System.String path, Boolean optional) [0x00000] in <filename unknown>:0
>   at Microsoft.Framework.ConfigurationModel.JsonConfigurationExtension.AddJsonFile (IConfigurationSourceRoot configuration, System.String path) [0x00000] in <filename unknown>:0
>   at OmniSharp.Startup..ctor () [0x00000] in <filename unknown>:0
>   at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0
>
> It'd be cool if this config option was supported
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OmniSharp/omnisharp-roslyn/issues/301>.
>
-- 
Thanks,
David

**Comment by nosami** [comment] 2015-09-17 16:14
This particular issue is probably fixed in the latest omnisharp-roslyn too. Not the configuration aspect, but the way that assemblies are compared.

**Comment by nosami** [comment] 2015-09-17 16:30
@FabioCZ Can you try omnisharp-atom out and see if the problem is there too? The latest omnisharp-roslyn fix is in atom as of yesterday?

**Comment by FabioCZ** [comment] 2015-09-17 16:53
Tried latest omnisharp with Atom, and the "Assuming assembly reference..." problem seems to be gone. Thanks

**Comment by aggieben** [comment] 2017-02-12 23:59
Is there anything since 2015 that would address this and related issues?  In my case,  OmniSharp is still a little behind with respect to the new RC4 tooling, so I see issues listed in the Problems tab; they are intellisense issues in csproj files relating to missing syntax that would be expected in MSBuild 12.0, but not in the lastest build tools.

**Comment by DustinCampbell** [comment] 2017-02-13 02:36
The latest version of omnisharp-roslyn is up-to-date with VS 2017 RC4 tooling. It even includes a build of MSBuild 15.0 inside of it.

**Comment by Leandros** [comment] 2018-03-06 11:39
Still not possible?

**Comment by divmgl** [comment] 2018-03-17 23:32
Any update on this? Seeing this with a Unity project on Sublime text. Would be nice to be able to be able to code without fifty warnings per file.

**Comment by filipw** [comment] 2019-06-20 07:03
I will close this as no longer valid - we don't support `IgnoredCodeIssues` anymore.
Instead you can control these behaviors using rulesets and - soon - using `.editorconfig` (#1526)

**Closed by filipw** 2019-06-20 07:03 UTC
Labels: feature request
