### ISSUE TITLE
Error Loading Analyzer Built TargetFramework > netstandard2.0

### ISSUE THREAD

**Issue by GordenOu** [OmniSharp/omnisharp-roslyn#2118] opened 2021-03-21 18:56 UTC
When a project references Roslyn Analyzer built with TargetFramework > netstandard2.0, Omnisharp will fail to load the package/project reference with the error log below:

https://github.com/OmniSharp/omnisharp-roslyn/blob/a8578acd91dd7699bdd012caf72645fa993bbcc2/src/OmniSharp.MSBuild/ProjectManager.cs#L521

The error message would be "Exception has been thrown by the target of an invocation."

I guess the reason is that the TargetFrameworks of Omnisharp.MSBuild is set to **net472;netcoreapp2.1**. The project file has not been updated for a long time:
https://github.com/OmniSharp/omnisharp-roslyn/blob/a8578acd91dd7699bdd012caf72645fa993bbcc2/src/OmniSharp.MSBuild/OmniSharp.MSBuild.csproj#L4

So please add net5.0 to TargetFrameworks. Is there any compatibility concern?

**Comment by filipw** [comment] 2021-03-21 19:11
Merely adding net5.0 to TargetFrameworks would not solve anything here, because the OmniSharp entrypoint process itself is only `net472` anyway (for compatibility reasons).

What is the use case you have? Which analyzer package doesn't work? Does it work in Visual Studio?

**Comment by GordenOu** [comment] 2021-03-22 02:17
I was trying to update an analyzer in my own project. I tried in Visual Studio and seems it doesn't work either, there will be a warning CS8032 with the same error message. In my case, netstandard2.0 with <LangVersion>9.0</LangVersion> would be a work around.

**Comment by filipw** [comment] 2021-03-22 07:57
Right, so Visual Studio runs on .NET Framework, same as OmniSharp and therefore this is an usupported scenario too - see https://github.com/dotnet/roslyn/issues/50914

This is currently by design, so I will close this. There is a `net5.0` branch for OmniSharp and in the future when OmniSharp process changes to .NET 5.0 it will work automatically, however, it is still not recommended to author analyzers like that, but the recommendation is to use `netstandard2.0` for analyzer portability. See https://github.com/dotnet/roslyn/issues/44251

**Closed by filipw** 2021-03-22 07:57 UTC
