### ISSUE TITLE
Roslynator.Analyzers 

### ISSUE THREAD

**Issue by timjroberts** [OmniSharp/omnisharp-roslyn#1496] opened 2019-05-15 12:26 UTC
The latest build of Omnisharp Roslyn fails to use the referenced `Roslynator.Analyzers` package for a given project, giving the following error repeated multiple times:
```
Could not load signature of Roslynator.CSharp.Analysis.UnconstrainedTypeParameterCheckedForNullAnalyzer:Analyze due to:
Could not load file or assembly 'Roslynator.CSharp, Version=1.0.0.8, Culture=neutral, PublicKeyToken=390be46f77b79f52' or one of its dependencies.
```
This has been working but appears to have begun failing since `1.32.19`. 

**dotnet --info**
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.203/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.1.202 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.2.101 [/usr/local/share/dotnet/sdk]
  2.2.203 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
**mono --version**
```
Mono JIT compiler version 5.18.1.3 (2018-08/fdb26b0a445 Wed Mar 20 10:02:02 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

**Comment by filipw** [comment] 2019-05-15 12:51
The analyzers are shadow copied since 1.32.19 so I suspect this is the root cause for the error https://github.com/OmniSharp/omnisharp-roslyn/pull/1474
do you have a repro project? can you post a full omnisharp log at debug level? which version of Roslynator.Analyzers is this, 2.0.0?

thanks

**Comment by timjroberts** [comment] 2019-05-16 07:05
Yes, version 2.0.0 of the `Roslynator.Analyzers` package.

I've just created a Console Application:
```
dotnet new sln -n AnalyzersTest
dotnet new console -n ConsoleApp
dotnet sln add ./ConsoleApp
dotnet add ./ConsoleApp/ package Roslynator.Analyzers -v 2.0.0
```
Reloaded the VS Code window, and all is working as expected. I get reported violations if I introduce one. It still fails in my existing project though. I've attached the Omnisharp Log at debug level. 
[omnisharp-debug.log.txt](https://github.com/OmniSharp/omnisharp-roslyn/files/3185763/omnisharp-debug.log.txt)

It may be Mono related? I did install VS for Mac 2019 which required the later Mono. I'll try downgrading Mono, but it doesn't explain why it works in a new solution.

**Comment by filipw** [comment] 2019-05-16 09:48
Fixed with https://github.com/OmniSharp/omnisharp-roslyn/issues/1496

**Closed by filipw** 2019-05-16 09:48 UTC

**Comment by timjroberts** [comment] 2019-05-17 13:59
Installed the latest VSCode (1.34.0) and the latest omnisharp.roslyn (1.32.20-beta.15) and all appears to be working again. 
Thanks @filipw and @savpek. Absolutely love have Analyzer support!

**Comment by filipw** [comment] 2019-05-17 14:21
oh great! 👍
