### ISSUE TITLE
The error and warning list increments with the same items after every typing. 

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#593] opened 2016-06-23 13:36 UTC
_From @heshuimu on June 22, 2016 11:32_
- VSCode Version: 1.2.1
- OS Version: macOS Sierra 10.12 Beta(16A201w)

Steps to Reproduce:

I was using VS Code with **Legacy OmniSharp** to develop Unity projects. There is a plugin I used has a wrapper script used a namespace that Unity somehow did not expose (although the code compiles since the namespace does exist), which shows as an error. There are also several warnings due to unnecessary using directives.Whenever I stop typing the error/warning counter would go up and it would be several duplicated entries for one error/warning. 
1. Open a Unity project and set up to use VS Code with [dotBunny/VSCode](https://github.com/dotBunny/VSCode).
2. Create a new script and write something so that it makes an error or a warning.
3. Create another script, and while writing things in it, watch the error/warning counters go up whenever OmniSharp does the check. Reveling the list will show duplicated error/waring items. 

_Copied from original issue: Microsoft/vscode#7996_

**Comment by DustinCampbell** [comment] 2016-11-02 13:36
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/587.

The legacy C# extension is no longer supported, but the C# extension fully supports Unity projects. Note that the very latest C# extension (1.5-beta4) should address this problem.

**Closed** 2016-11-02 13:36 UTC
Labels: duplicate
