### ISSUE TITLE
Microsoft.Build.Exceptions.InvalidProjectFileException: Items that are outside Target elements must have one of the following operations: Include, Update, or Remove.

### ISSUE THREAD

**Issue by RononDex** [OmniSharp/omnisharp-roslyn#1549] opened 2019-07-11 08:12 UTC
Since the merge of https://github.com/OmniSharp/omnisharp-roslyn/commit/c2c6cfca3032d0bad1628e16333c76cf83d114fb symbols are no longer analyzed unless I open the file containing them and hit Ctrl+S to force analysis of the file.

If I search for a symbol with "#SymbolName" it won't find it, even though the output of omnisharp shows that everything was analyzed. As soon as I open the file containing the symbol and hit Ctrl+S omnisharp starts analyzing the file and caches the symbols, making them findable.

Further, since the files arent analysed, CodeLense does not show "xx references" on functions, classes, etc in the opened file until Ctrl+S is hit to analayse the file

This is in VSCode.

UPDATE:
Just found several of those exceptions in omnisharp log when loading projects:
Microsoft.Build.Exceptions.InvalidProjectFileException: Items that are outside Target elements must have one of the following operations: Include, Update, or Remove.

**Comment by filipw** [comment] 2019-07-11 08:45
This is not caused by https://github.com/OmniSharp/omnisharp-roslyn/commit/c2c6cfca3032d0bad1628e16333c76cf83d114fb, it doesn't impact the symbol search.
Could you please provide a repro / example of the project files you have that cause the error?

**Comment by savpek** [comment] 2019-07-11 08:45
Cannot repro issue locally 😢  can you share broken csproj file? It may be releated https://github.com/OmniSharp/omnisharp-roslyn/commit/4de169b1b318f27c644e45e485b3c22312dab2c4 since they merged about same time.

**Comment by RononDex** [comment] 2019-07-11 08:48
I can not share sadly due to it being a solution from work (with quite a lot of code).

I noticed this exception in omnisharp  when loading projects:
Microsoft.Build.Exceptions.InvalidProjectFileException: Items that are outside Target elements must have one of the following operations: Include, Update, or Remove.

seems the analysis works for some projects but not for others, the ones throwing that exception are not analaysed

**Comment by filipw** [comment] 2019-07-11 08:52
do you have any entries for `<AdditionalFiles />` in the project files?

**Comment by RononDex** [comment] 2019-07-11 09:07
I did take a look at the csproj files, turns out they had some invalid <ItemGroup> inside with invalid elements (somebody confused app.config with .csproj). Not sure why it worked with the old build though.

**Comment by filipw** [comment] 2019-07-11 09:11
OK then it is "by design", I will close the issue.
To be honest, the bundled version with extension 1.20 and the current master of OmniSharp (`"omnisharp.path": "latest"`) are already quite far apart, including a different compiler version that they are using.

If you run into troubles again, feel free to open a new issue (ideally, with repro steps 😀)

**Closed by filipw** 2019-07-11 09:11 UTC

**Comment by RononDex** [comment] 2019-07-11 10:21
Still having issues with "latest" version:
CodeLense appears to not be working:
![image](https://user-images.githubusercontent.com/2249071/61043381-65566380-a3d6-11e9-9535-166bcfa1a910.png)
This is after having VSCode open untouched for like 1hour, so it should definitely have analyzed everything already.

**Comment by 19lawrence83** [comment] 2024-03-08 20:47
Had a similar issue when trying to make a master build proj. 

You might try checking the case of your include. Just making mine Include worked.
