### ISSUE TITLE
System.DllNotFoundException: System.Native

### ISSUE THREAD

**Issue by andrevdm** [OmniSharp/omnisharp-roslyn#600] opened 2016-07-04 08:17 UTC
When I try run .net 4.5.1 OminSharp I get an exception saying System.Native can not be found. The coreclr versions works (it has System.Native.so locally) but that wont load my solutions which are not coreclr.

Is this a known issue? Do I need to install any extra support libs? I can't see anything I'm missing according to the docs.

Thanks

Using
   omnisharp-roslyn/artifacts/publish/OmniSharp/default/net451/OmniSharp.exe

Github sha
   e01e8ae5b64ec25504c5a39b74ad27a7e0cd6161

Linux version
  4.4.0-21-generic #37-Ubuntu 16.04

mono version
   Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

Exception

```
OmniSharp: 

Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: System.Native
  at (wrapper managed-to-native) Interop+Sys:GetUnixNamePrivate ()
  at Interop+Sys.GetUnixName () <0x41b3ed50 + 0x0000b> in <filename unknown>:0 
  at System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform (OSPlatform osPlatform) <0x41b3ece0 + 0x00023> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLogger..ctor (System.String name, System.Func`3 filter, Boolean includeScopes) <0x41b3e700 + 0x00153> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLoggerImplementation (System.String name) <0x41b3e060 + 0x0007b> in <filename unknown>:0 
  at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (System.Collections.Concurrent.TKey key, System.Func`2 valueFactory) <0x7fd26d327c10 + 0x00066> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLogger (System.String name) <0x41b3df70 + 0x000bb> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Logger.AddProvider (ILoggerProvider provider) <0x41b3de50 + 0x0002a> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.LoggerFactory.AddProvider (ILoggerProvider provider) <0x41b3d8b0 + 0x0015b> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole (ILoggerFactory factory, System.Func`3 filter, Boolean includeScopes) <0x41b3d4d0 + 0x00058> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole (ILoggerFactory factory, System.Func`3 filter) <0x41b3d4a0 + 0x00017> in <filename unknown>:0 
  at OmniSharp.Startup.Configure (IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor) <0x41ab9730 + 0x005d3> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7fd26d5ab9e0 + 0x000a1> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize () <0x41a9e8d0 + 0x0001f> in <filename unknown>:0 
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build () <0x41a903a0 + 0x00127> in <filename unknown>:0 
  at OmniSharp.Program.Main (System.String[] args) <0x41a7f100 + 0x00a62> in <filename unknown>:0 
  at Program.Main (System.String[] args) <0x41a7dd50 + 0x0012f> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: System.Native
  at (wrapper managed-to-native) Interop+Sys:GetUnixNamePrivate ()
  at Interop+Sys.GetUnixName () <0x41b3ed50 + 0x0000b> in <filename unknown>:0 
  at System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform (OSPlatform osPlatform) <0x41b3ece0 + 0x00023> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLogger..ctor (System.String name, System.Func`3 filter, Boolean includeScopes) <0x41b3e700 + 0x00153> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLoggerImplementation (System.String name) <0x41b3e060 + 0x0007b> in <filename unknown>:0 
  at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (System.Collections.Concurrent.TKey key, System.Func`2 valueFactory) <0x7fd26d327c10 + 0x00066> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLogger (System.String name) <0x41b3df70 + 0x000bb> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Logger.AddProvider (ILoggerProvider provider) <0x41b3de50 + 0x0002a> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.LoggerFactory.AddProvider (ILoggerProvider provider) <0x41b3d8b0 + 0x0015b> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole (ILoggerFactory factory, System.Func`3 filter, Boolean includeScopes) <0x41b3d4d0 + 0x00058> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole (ILoggerFactory factory, System.Func`3 filter) <0x41b3d4a0 + 0x00017> in <filename unknown>:0 
  at OmniSharp.Startup.Configure (IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor) <0x41ab9730 + 0x005d3> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7fd26d5ab9e0 + 0x000a1> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize () <0x41a9e8d0 + 0x0001f> in <filename unknown>:0 
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build () <0x41a903a0 + 0x00127> in <filename unknown>:0 
  at OmniSharp.Program.Main (System.String[] args) <0x41a7f100 + 0x00a62> in <filename unknown>:0 
  at Program.Main (System.String[] args) <0x41a7dd50 + 0x0012f> in <filename unknown>:0 
```

**Comment by andrevdm** [comment] 2016-07-04 08:24
Seems to be this: https://github.com/dotnet/corefx/issues/9012

Does this mean I can't currently use OmniSharp for mono based projects?

**Comment by BeeWarloc** [comment] 2016-07-04 11:34
I ran into this problem, and were able to work around it by manually copying `~/.nuget/packages/runtime.ubuntu.16.04-x64.runtime.native.System/1.0.1/runtimes/ubuntu.16.04-x64/native/System.Native.so` to `.nuget/packages/runtime.ubuntu.16.04-x64.runtime.native.System/1.0.1/runtimes/ubuntu.16.04-x64/native/System.Native.so/libSystem.Native.so`.

However, when running it did not seem to work very well for the project I attempted to open. I haven't had time to investigate exactly why yet, so it might have been something I did wrong..

**Comment by andrevdm** [comment] 2016-07-04 12:21
@BeeWarloc Thanks. If I copy System.Native.so into the root of the project folder then OmniSharp does start (I assume I can copy the .so to the shared libs folder too later on). But as you say 99% of my projects fail to load with an error of "Failed to process project file". I'll see if I can get some time to look further

**Comment by borgdylan** [comment] 2016-07-04 16:37
See: https://github.com/borgdylan/corefx/tree/sysnative_standalone2/src/Native/System.Native

**Comment by andrevdm** [comment] 2016-07-04 19:49
@borgdylan Can I build that folder with the included makefile and then replace the System.Native.so? Do you know if the error I mentioned about ominsharp failing to process the project files is related? Thanks

**Comment by borgdylan** [comment] 2016-07-04 19:52
Yes you shoudl try that makefile. I would use the install target. It makes it available system wide.

**Comment by andrevdm** [comment] 2016-07-04 20:08
@borgdylan Thanks, building that from the sysnative_standalone2 does work and install a libSystem.Native.so. 

I'm am still getting the "Failed to process project file" error though. I'll have to dig a bit more and see if omnisharp logs more detail somewhere. 

Thanks for the help with System.Native.so

**Comment by DustinCampbell** [comment] 2016-11-11 00:56
For Mono, the fix is to just delete System.Runtime.InteropServices.RuntimeInformation.dll from the OmniSharp output. The problem is that Mono isn't really supported by the .NET CLI. So, binaries can get pulled in that aren't necessary. In this particular case, the correct facade for that binary already exists in Mono. So, if you're building a net46 app on OSX to run on Mono, you don't need that binary at all.

**Comment by mickaelistria** [comment] 2017-07-13 13:37
@DustinCampbell The suggested workaround doesn't work for me:

```
mistria@mistria-rh:~/omnisharp-mono$ rm *RuntimeInformation*
mistria@mistria-rh:~/omnisharp-mono$ mono OmniSharp.exe
OmniSharp: 
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize () [0x00008] in <24af31b64ae843689736582353a19b3a>:0 
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build () [0x0008a] in <24af31b64ae843689736582353a19b3a>:0 
  at OmniSharp.Program+<>c__DisplayClass1_0.<Run>b__1 () [0x00196] in <372033fc0ebc4984ad95c71bb1d0cc59>:0 
  at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute (System.String[] args) [0x0035b] in <e56ebbc3ed87488b8e26736bbadaa5d3>:0 
  at OmniSharp.Program.Run (System.String[] args) [0x001ae] in <372033fc0ebc4984ad95c71bb1d0cc59>:0 
  at OmniSharp.Program.Main (System.String[] args) [0x0001c] in <372033fc0ebc4984ad95c71bb1d0cc59>:0 
mistria@mistria-rh:~/omnisharp-mono$ mono --version
Mono JIT compiler version 4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15 15:23:40 UTC 2017)
```

I'm using the version that's fetched by omnisharp-node-client, so apparently v1.21.0

**Comment by r03** [comment] 2017-07-31 19:28
I had the same problem. Compiling worked with the mono 5.2.0 package, but running omnisharp-vim/omnisharp-roslyn/artifacts/scripts/OmniSharp failed.
After getting the latest Omnisharp-roslyn from git I noticed there  are two scripts. OmniSharp (net46) and OmniSharp.Core (netcoreapp1.1). 
But I think omnisharp-vim always starts the OmniSharp script?

In the end I just downloaded a release from here: https://github.com/OmniSharp/omnisharp-roslyn/releases

I then changed omnisharp-vim/omnisharp-roslyn/artifacts/scripts/OmniSharp to something like this:

```
#!/bin/bash
"/Users/roeland/.vim/plugged/omnisharp-vim/omnisharp-osx-x64-netcoreapp1.1/Omnisharp" "$@"
```

Now it works

**Comment by filipw** [comment] 2022-03-25 14:56
I will close this as obsolete. Please open a new issue if this still happens with the latest OmniSharp build.

**Closed by filipw** 2022-03-25 14:56 UTC
