### ISSUE TITLE
Improve formatting options experience

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#366] opened 2015-12-15 10:29 UTC
_From @anfomin on December 14, 2015 17:34_

I've configured VS Code to always use tabs:

``` json
// Place your settings in this file to overwrite the default settings
{
    "editor.insertSpaces": false
}
```

But C# **Format Code** command (Shift+Alt+F) always replaces tabs with spaces. I'm using OS X El Capitan.

_Copied from original issue: Microsoft/vscode#1300_

**Comment by jrieken** [comment] 2015-12-15 10:29
This is because OmniSharp doesn't support per request formatting options (https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Abstractions/Models/v1/FormatRangeRequest.cs#L6). Moving to OmniSharp for that.

**Comment by jrieken** [comment] 2015-12-15 10:29
@anfomin - Do workaround this, you can create an `omnisharp.json` with the config

**Comment by anfomin** [comment] 2016-06-18 10:24
@jrieken I tried to create `omnisharp.json` in my project room directory with content:
```json
{
	"TextEditorOptions": {
		"tabsToSpaces": false
	}
}
```

But `Format Code` command still uses spaces.

**Comment by anfomin** [comment] 2016-06-18 10:26
I have found file I needed:
```json
{
	"FormattingOptions": {
		"useTabs": true
	}
}
```

Now it's OK.

**Comment by 0xdeafcafe** [comment] 2016-12-19 15:36
Is there a way to affect omnisharp globally with the method above?

**Comment by filipw** [comment] 2016-12-19 15:56
here is a new wiki article I just posted today, hopefully this helps 
https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration%20Options

When the new C# Extension for VS Code is released, the VS Code intendation/tab settings will be inherited by OmniSharp automatically.

**Comment by DustinCampbell** [comment] 2016-12-23 12:37
There are two things that we need to support to improve the experience.

1. The omnisharp.json file should be reloaded when it changes so that users don't have to restart OmniSharp after changing this file.
2. We need a new end point for specifying formatting options. This will allow hosts to pass along options that aren't stored in omnisharp.json file. (E.g. omnisharp-vscode passes the "editor.insertSpaces" and "editor.tabSize" VS Code options along as "formattingOptions:useTabs", "formattingOptions:tabSize" and "formattingOptions:indentationSize" to OmniSharp.

**Comment by filipw** [comment] 2016-12-23 13:52
I can go ahead and implement this

**Comment by Thaina** [comment] 2016-12-24 06:07
I'm not so sure that omnisharp itself was normally listening to files changed in workspace, or is it?
Or it was designed to be restarted when omnisharp.json was changed and it is extension responsible to call omnisharp restart command?

Also if there are per request formatting options supported. What would happen to omnisharp.json when there is command to change? Would it keep track of change?

What would happen if we have omnisharp.json to set tabSize to 2
Then call command to change it to 3
Then modified omnisharp.json to set tabSize to 4

Another scenario is 
we have omnisharp.json to set tabSize:2 and useTabs:false
Then call command to set tabSize:3 and useTabs:true
Then modified omnisharp.json to set tabSize to 4, is the useTabs would be override?

In my opinion omnisharp.json should contains all configurations values that changed from default in workspace

**Comment by kenning** [comment] 2018-09-03 02:57
Not sure exactly what's wrong here, but when I run code formatting it uses 4 space indentations. Other formatting options seem to work, like `    "NewLinesForBracesInTypes": true,` work after I change them. (I definitely do not have separate omnisharp.json files for this project overriding this.)

Side note, the casing for omnisharp.json on the wiki file (https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration%20Options) seems to be inconsistent, too. FormattingOptions is sometimes pascal-cased and sometimes camel-cased, as is TabSize, in different areas of the file. I guess it doesn't change anything because I tried all possible combinations but none worked for me, you may want to mention that it's agnostic if it actually is.

Other than that issue, the wiki article is pretty clear, so nice job

**Comment by filipw** [comment] 2020-07-28 07:15
I will close this as implemented.

 - changes in omnisharp.json are now watched in real time 
 - we have editorconfig support which is also watched in real time
 - omnisharp.json options are not case-sensitive

**Closed by filipw** 2020-07-28 07:15 UTC
Labels: 0 - Backlog
