### ISSUE TITLE
1.32.20 and 1.32.21-beta.156 are broken on .NET Core 3.0 preview6

### ISSUE THREAD

**Issue by AlseinX** [OmniSharp/omnisharp-roslyn#1537] opened 2019-07-01 04:06 UTC
```
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        Ancfi.Hosting: Found implicit package reference 'Microsoft.NETCore.App', but none of the versions in the lock file ("3.0.0-preview6-27804-01") satisfy [3.0.0, )
```

**Comment by AlseinX** [comment] 2019-07-01 09:59
I tried to restart the OS and there were no problems, but I have no idea how this problem could present

**Comment by filipw** [comment] 2019-07-05 08:48
i'll close this as duplicate of #1541

**Closed by filipw** 2019-07-05 08:48 UTC
