### ISSUE TITLE
.NET Core Omnisharp variant fails to load .NET Core projects

### ISSUE THREAD

**Issue by danwalmsley** [OmniSharp/omnisharp-roslyn#849] opened 2017-05-05 16:01 UTC
Step to reproduce:

Use this version:
https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.17.0/omnisharp-ubuntu.16.10-x64-netcoreapp1.1.tar.gz

then do dotnet new console

and then run

omnisharp -s ~/projectdir

will post the output I'm seeing later on...

**Comment by DustinCampbell** [comment] 2017-05-05 16:17
Ah, this is with a netcoreapp1.1 release of OmniSharp. In our Slack chat, I had assumed it was a Mono build. These really don't work all that well for MSBuild work FWIW, and we'll be moving OmniSharp off of CoreCLR and onto an embedded mono soonish (#666).

Recently, I made a change to *stop* shipping the Sdks (e.g. Microsoft.Net.Sdk) with OmniSharp and allow MSBuild to use the Sdks included with the .NET Core SDK matched to the project its loading. That PR is here. You might consider reverting those changes locally and seeing if that fixes the problem for you.

It seems like the CoreCLR version isn't locating the assemblies next to the ResolvePackageDependencies task (which is included in Microsoft.NET.Build.Tasks.dll). The task references more recent dev builds of NuGet packages than are available on www.nuget.org. I would expect the CoreCLR to load the NuGet.ProjectModel.dll that is sitting next to Microsoft.NET.Build.Tasks.

FWIW, I can repro this on OSX as well, with the netcoreapp1.1 version of OmniSharp.

**Comment by DustinCampbell** [comment] 2017-05-05 16:49
I can also repro on Windows. This seems a .NET Core assembly loading issue. I can launch the net46 OmniSharp with a .NET Core 2.0 project and it loads properly. However, if I launch the netcoreapp1.1 OmniSharp with a .NET Core 2.0 project, it fails to load properly.

**Comment by DustinCampbell** [comment] 2017-05-05 18:12
OK. I don't need your additional log. I can definitely reproduce the issue here.

The problem is a general issue with .NET Core. Because we use MSBuild in-proc, the dependencies of any task that gets run must be in the deps.json file. I'm going to add those references back conditioned on .NET Core and see if it addresses the problem. However, this isn't a very good solution. I honestly don't know how to have a good solution on .NET Core. 😞

Seems like I should get working on #666.

**Comment by DustinCampbell** [comment] 2017-05-05 18:49
Actually, adding the references back doesn't work unless I also update OmniSharp to target the newer dev-build NuGet binaries that the preview CLI is using because NuGet only has 4.0.0 versions of these assemblies available on nuget.org. I'm actually not sure how to fix this without doing one of the following:

1. Ship the Sdks with OmniSharp, which has significant issues in that we don't use the Sdks that a project targets.
2. Include the same NuGet references as the Sdks do. This is not a longterm solution and will eventually break.

**Comment by jphenow** [comment] 2017-05-26 19:00
VS Code C# plugin just updated - would this issue be related to why I'm seeing:

```
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "~/.vscode/extensions/ms-vscode.csharp-1.10.0/bin/omnisharp/msbuild/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. 
```

**Comment by DustinCampbell** [comment] 2017-06-06 22:51
@jphenow: Sorry, I just saw your post here. No, this wouldn't be released to that.

**Comment by DustinCampbell** [comment] 2017-08-09 00:43
I think this issue can go away now that there aren't .NET Core variants of OmniSharp after #915 was merged.

**Closed by DustinCampbell** 2017-08-09 00:43 UTC
Labels: bug
