### ISSUE TITLE
Ignoring some C# warnings of OmniSharp

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#361] opened 2015-12-10 11:50 UTC
_From @zsombornagy on December 7, 2015 16:20_

Hi!

I'm trying to ignore the "Unnecessary using directive." warning in my C# code (for Unity3D).
I've created an `omnisharp.json` file with this content:

```json
{
	"IgnoredCodeIssues": [
		"^Unnecessary using directive.$"
	]
}
```

Then I opened a C# file, and restarted OmniSharp (with the command palette within Code).
But it fails with this message:

```
System.FormatException: Unsupported JSON token 'StartArray' was found. Path 'IgnoredCodeIssues', line 2 position 24.
```

I'm using VS Code Version 0.10.3, on OS X 10.11.1.

Thanks!

_Copied from original issue: Microsoft/vscode#1076_

**Comment by jrieken** [comment] 2015-12-10 11:50
I don't believe that supported like that, but moving to OmniSharp for comment first.

**Comment by filipw** [comment] 2016-03-20 02:59
This is currently not supported yet, it was mentioned/suggested before here https://github.com/OmniSharp/omnisharp-roslyn/issues/301 but the actual feature was never implemented.

I suggest to close on of the two issues as duplicate

**Comment by filipw** [comment] 2016-03-22 13:58
Closing as duplicate of #301

**Closed by filipw** 2016-03-22 13:58 UTC
