### ISSUE TITLE
New analyzer API (DiagnosticSuppressor) is not supported

### ISSUE THREAD

**Issue by sailro** [OmniSharp/omnisharp-roslyn#1711] opened 2020-02-12 18:48 UTC
I'm using a pack of Roslyn Analyzers built from:
https://github.com/microsoft/Microsoft.Unity.Analyzers

On a Unity project (Game engine) available here:
https://learn.unity.com/project/roll-a-ball-tutorial

When using Visual Studio:
![image](https://user-images.githubusercontent.com/638167/74366012-0863c700-4d84-11ea-81c3-746c47b97f4a.png)

When using VSCode:
![image](https://user-images.githubusercontent.com/638167/74366078-26312c00-4d84-11ea-9b9e-da4e5b782efd.png)

Omnisharp is able to correctly consume regular Analyzers (see `UNT0009`). But Diagnostic suppressors are not supported:
```
"Private member 'ReadmeEditor.Awake' is unused. [Assembly-CSharp-Editor]"
```
This message is correctly suppressed in the VS context, but not within VSCode.

The code for this suppressor is here:
https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/src/Microsoft.Unity.Analyzers/UnusedMessageSuppressor.cs

The Roslyn team added a new API regarding programmatic suppression of diagnostics:
https://github.com/dotnet/roslyn/pull/36067

**Comment by filipw** [comment] 2020-02-12 19:03
thanks for the issue, this is indeed currently not supported

**Comment by sailro** [comment] 2020-02-12 19:18
@mavasani did this great job of adding this new DiagnosticSuppressor API. Perhaps supporting this in OmniSharp is not that complicated (host initialization?).

**Comment by loligans** [comment] 2020-02-20 18:05
@sailro, @filipw I think I may have gotten around this issue by enabling **roslyn analyzers** _and_ **editorconfig** support. You can configure the rules you want enabled or disabled globally within your `.editorconfig` file. 

**_Note_**: After enabling **roslyn analyzers** _and_ **editorconfig** support, Omnisharp will require to be restarted in order for the changes to take effect. In addition, OmniSharp needs to be restarted after you make any changes to your `.editorconfig` file. 

Aside from the inconvenience of having to reload OmniSharp everytime I make a changes to my `.editorconfig`, one annoyance I have with this setup is that I am unable to disable analysis of specific files or directories. 

As a user sometimes I would like to be able to exclude specific files or directories from analysis. An example would be auto generated files from an EF Core migration. @savpek do you know if specific files or directories can be excluded from OmniSharp file analysis?

**Comment by savpek** [comment] 2020-02-22 07:59
@loligans have you tested suppres message attributes where specifically following: 

namespaceanddescendants - (Requires compiler version 3.x or higher and Visual Studio 2019) This scope suppresses warnings in a namespace and all its descendant symbols. The namespaceanddescendants value is ignored by legacy analysis.

Which seems roslyn way to do similar thing. However i have never tested those with omnisharp so they may or may not work. If they don't that is very good feature to add 🤔

**Comment by loligans** [comment] 2020-04-22 23:52
@savpek Sorry, I'm not sure how to do what you're suggesting. 

What I have tried is to disable the analyzers that pollute the VSCode Problems Pane by using a nested `.editorconfig` inside the `Migrations` directory. Unfortunately, that had no effect on Omnisharp's analysis.

**Comment by mavasani** [comment] 2020-04-22 23:58
@loligans have you tried https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-of-multiple-analyzer-rules-at-once-in-an-editorconfig-file?

Dropping an editorconfig with the following contents in any folder should ensure no analyzer diagnostics reported within it, unless some parent directory is explicitly enabling some rules.

```
[*.cs]
dotnet_analyzer_diagnostic.severity = none
```

Another approach is trying out .editorconfig with following contents, which will treat the entire folder and sub-folders as generated code, which should filter almost all analyzer diagnostics (except the critical ones like some security rules which explicitly want to flag generated code)

```
[*.cs]
dotnet_analyzer_diagnostic.severity = none
```

**Comment by mavasani** [comment] 2020-04-23 00:01
NOTE: The suggested feature above needs "Visual Studio 2019 version 16.5 or later"

**Comment by loligans** [comment] 2020-04-23 00:10
Thank you for the help @mavasani. Applying the suggested configuration unfortunately did not solve the issue. I should note that I am running on Linux, so I do not have Visual Studio 2019 installed.

VSCode Version: 1.44.2
Omnisharp: Latest

**Comment by mavasani** [comment] 2020-04-23 00:23
What version of Roslyn compiler do you have? This is a compiler feature added in version 3.5.0 of the compiler, so should work even in other hosts.

**Comment by loligans** [comment] 2020-04-23 00:37
It's not clear to me exactly how to get the Roslyn compiler version. However, when I run `dotnet build` I get the following:
```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```

Is **16.4.0+e901037fe** close to what you're looking for?

**Comment by mavasani** [comment] 2020-04-23 01:41
> 16.4.0+e901037fe 

That indicates you are on MSBuild toolset that shipped with VS2019 16.4. So you will need 16.5 version of it...

**Comment by loligans** [comment] 2020-05-14 05:21
I can confirm the issue I was experiencing is resolved using the latest build of the vscode extension (`v1.21.19-beta1`). The suggestion below is what worked for me. 
```
[*.cs]
generated_code = true
```

**Comment by mavasani** [comment] 2020-05-14 05:31
Thanks, now officially documented at https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#configure-generated-code

**Comment by alexrp** [comment] 2020-05-21 00:02
Worth noting that `DiagnosticSuppressor` support is important for [Microsoft's Unity analyzers](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/doc/index.md#diagnostic-suppressors).

**Comment by heshuimu** [comment] 2020-10-05 04:34
+1 for Unity Analyzers. This could especially be useful to silence invalid warnings from other analyzers on Unity methods:
```csharp
// CA1822: Member 'Awake' does not access instance data and can be marked as static. 
// IDE0051 : Private member 'TouchOnScreenTest.Awake' is unused. 
private void Awake()
{
	Application.targetFrameRate = 120;
}
```

**Comment by marcospgp** [comment] 2020-12-11 11:31
So is there no way currently to enable the Unity analyzers on VSCode?

**Comment by marcospgp** [comment] 2020-12-12 12:55
I figured this out more or less, and posted [a Reddit thread](https://www.reddit.com/r/Unity3D/comments/kbonih/how_to_enable_unity_warnings_in_visual_studio_code/) explaining how to set up the Unity analyzers with Omnisharp in Visual Studio Code. Hope it helps someone because it took me 2 days to figure it out!

**Comment by sbaranov** [comment] 2020-12-12 17:31
There is a problem in omnisharp support for .editorconfig. Whenever the project is updated outside of vscode, omnisharp dynamically reloads the project, but forgets to use .editorconfig at that point, so all settings gets reset - all warnings become enabled, all formatting rules switch to defaults, etc. This means that whenever you switch git branches, or make any change in Unity that affects the project such as adding a new script, you suddenly see thousands of unrelated warnings in vscode that shouldn't be there. One workaround is to restart vscode every time omnisharp lost its settings, which basically becomes every few minutes if you're actively editing.

**Comment by filipw** [comment] 2020-12-12 18:30
@sbaranov this was fixed in https://github.com/OmniSharp/omnisharp-roslyn/pull/2028 which will be in the next release

**Comment by marcospgp** [comment] 2020-12-12 20:44
@filipw That's good to hear! Is there an expected release date for supporting the Unity suppressors (the original intention of this issue)?

It's interesting that Unity & Microsoft are sort of partnering up to get Unity working well with VSCode, but the workhorse under the whole thing is being maintained entirely by you 😅

**Comment by filipw** [comment] 2020-12-12 20:53
unfortunately the suppressors haven't been looked at yet, I am very sorry. Will try to prioritize this!
I usually put highest priority on things that I personally use 😂

> It's interesting that Unity & Microsoft are sort of partnering up to get Unity working well with VSCode, but the workhorse under the whole thing is being maintained entirely by you 😅

That is very kind of you to say! but there are over 100 contributors here https://github.com/OmniSharp/omnisharp-roslyn/graphs/contributors and currently a group of 4 maintainers (the ones seen on PR reviews).

**Comment by marcospgp** [comment] 2021-01-03 17:17
@filipw This functionality is now [part of the official VSCode documentation](https://code.visualstudio.com/docs/other/unity#_enabling-unity-warnings). It would be great to get the supressors working as well!

**Comment by WeirdBeardDev** [comment] 2021-01-09 19:27
@marcospgp 
> Edit 2: I created a .editorconfig file in the root folder of the project and that worked, but the line `generated_code = true` just silenced all of my warnings. What was that supposed to solve?

I solved this in the root .editorconfig by creating a separate header and then adding the generated code line.  In this way I could turn off all warning for downloaded or imported code, e.g., TextMesh Pro.

```
[Assets/TextMesh Pro/**.cs]
generated_code = true
```

**Comment by WeirdBeardDev** [comment] 2021-03-13 14:27
> unfortunately the suppressors haven't been looked at yet, I am very sorry. Will try to prioritize this!

@filipw any updates on this issue?

**Comment by filipw** [comment] 2021-03-13 14:32
no

**Comment by marcospgp** [comment] 2021-06-20 15:19
Seems like we are having some updates on this!!

**Closed** 2021-06-30 11:14 UTC
Labels: analyzers

**Comment by manfred-brands** [comment] 2021-11-06 09:53
@filipw I have just upgrade to vscode version 1.62.0. However, I still get issues that I know are suppressed by nunit.analyzers.
The below code does not show any error in VS2019 (16.11.5), nor when compiling with dotnet, but does show a _Dereference of a possible null reference` in vscode.

```
[Test]
public void Test()
{
    string? message = OptionalMessage();

    Assert.That(message, Is.Not.Null); // nunit.analyzers will suppress the possible null reference exception on the next line.
    Assert.That(message.Length, Is.GreaterThan(0));
}

private static string? OptionalMessage() => string.Empty;
```

I know that the nunit.analyzers are loaded as I can get violations against other rules to show up.

Is there anything I need to configure or do the analyzers need to do something different for vs-code to recognize the suppressor?
