### ISSUE TITLE
start server on mac os failed

### ISSUE THREAD

**Issue by sandao** [OmniSharp/omnisharp-roslyn#817] opened 2017-04-07 08:26 UTC
OS X 10.12.4

OmniSharp:
```
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location '/Users/Sandao/Projects/Unity/AGame' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in /Users/Sandao/Projects/Unity/AGame
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Resolving projects references
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBUILD_EXE_PATH environment variable set to /usr/local/Cellar/omnisharp/1.13.0/libexec/msbuild/MSBuild.dll
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBuildExtensionsPath environment variable set to /usr/local/Cellar/omnisharp/1.13.0/libexec/msbuild
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBuildSDKsPath environment variable set to /usr/local/Cellar/omnisharp/1.13.0/libexec/msbuild/Sdks
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Detecting projects in '/Users/Sandao/Projects/Unity/AGame/AGame.sln'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project from '/Users/Sandao/Projects/Unity/AGame/Assembly-CSharp.csproj'.
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to process project file '/Users/Sandao/Projects/Unity/AGame/Assembly-CSharp.csproj'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project from '/Users/Sandao/Projects/Unity/AGame/Assembly-CSharp-Editor.csproj'.
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to process project file '/Users/Sandao/Projects/Unity/AGame/Assembly-CSharp-Editor.csproj'.
info: OmniSharp.Script.ScriptProjectSystem[0]
      Detecting CSX files in '/Users/Sandao/Projects/Unity/AGame'.
info: OmniSharp.Script.ScriptProjectSystem[0]
      Could not find any CSX files
info: OmniSharp.Startup[0]
      Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
info: OmniSharp.Startup[0]
      Configuration finished.
```

**Comment by DustinCampbell** [comment] 2017-04-07 15:18
It looks like OmniSharp was successful launching (no failures) but it couldn't locate reference assemblies for your project. It does this by looking for the location of mono on the system. Is Mono on your path? Could you run `mono --version` post the output?

**Comment by sandao** [comment] 2017-04-08 05:24
@DustinCampbell 
Mono JIT compiler version 4.8.0 (Stable 4.8.0.524/9d74414 Thu Apr  6 19:26:41 BST 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by indie21** [comment] 2017-04-09 03:09
i face the same problem because of the sln is a unity project .

**Comment by DustinCampbell** [comment] 2017-04-09 05:12
@indie21: We support unity projects, so I don't think that would be the reason for the issue.

**Comment by DustinCampbell** [comment] 2017-04-09 05:19
@sandao, I've got a few other questions:

1. Are you using Bash as your shell, or have you changed the default to something else? (e.g. zsh)
2. Could you run `which mono` at a shell prompt and let me know where Mono is located?
3. Would you be willing to enable "debug" level logging for OmniSharp and post the output here? Here are instructions for doing that:
    1. In VS Code, select Preferences->Settings from the menu and add `"omnisharp.loggingLevel": "debug"` to your settings.json.
    2. Close VS Code and open it again with your solution.
    3. Select View->Output from the menu to display the Output pane and choose "OmniSharp Log" from the drop-down in the top-right corner.
    4. Copy and paste the content of the Output pane here.

**Comment by sandao** [comment] 2017-04-09 08:41
@DustinCampbell 
1.I use zsh
2.run which mono : /usr/local/bin/mono
3.I use emacs not VS Code,but I download VS Code just now, and use it open my project, it works normal，log here：
Starting OmniSharp server at 4/9/2017, 4:31:11 PM
    Target: /Users/Sandao/Projects/Unity/AGame/AGame.sln

OmniSharp server started wth Mono
    Path: /Users/Sandao/.vscode/extensions/ms-vscode.csharp-1.8.1/bin/run
    PID: 9500

OmniSharp: -s /Users/Sandao/Projects/Unity/AGame/AGame.sln --hostPID 9477 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel debug formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
﻿﻿{"Event":"log","Body":{"LogLevel":"DEBUG","Name":"OmniSharp.Startup","Message":"Loaded OmniSharp.DotNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"},"Seq":1,"Type":"event"}
[dbug]: OmniSharp.Startup
        Loaded OmniSharp.DotNetTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.Startup
        Loaded OmniSharp.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.Startup
        Loaded OmniSharp.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.Startup
        Loaded OmniSharp.Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.Startup
        Loaded OmniSharp.Roslyn, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.Startup
        Loaded OmniSharp.Roslyn.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.Startup
        Loaded OmniSharp.Script, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.Startup
        Loaded OmniSharp.Stdio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location '/Users/Sandao/Projects/Unity/AGame' on host 9477.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/Sandao/Projects/Unity/AGame
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBUILD_EXE_PATH environment variable set to /Users/Sandao/.vscode/extensions/ms-vscode.csharp-1.8.1/bin/omnisharp/msbuild/MSBuild.dll
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildExtensionsPath environment variable set to /Users/Sandao/.vscode/extensions/ms-vscode.csharp-1.8.1/bin/omnisharp/msbuild
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildSDKsPath environment variable set to /Users/Sandao/.vscode/extensions/ms-vscode.csharp-1.8.1/bin/omnisharp/msbuild/Sdks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in '/Users/Sandao/Projects/Unity/AGame/AGame.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/Users/Sandao/Projects/Unity/AGame/Assembly-CSharp.csproj'.
Discovered Mono file path: /usr/local/bin/mono
Resolved symbolic link for Mono file path: /usr/local/Cellar/mono/4.8.0.524/bin/mono-sgen
[dbug]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Using TargetFrameworkRootPath: /usr/local/Cellar/mono/4.8.0.524/lib/mono/xbuild-frameworks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: /Users/Sandao/Projects/Unity/AGame/Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/Users/Sandao/Projects/Unity/AGame/Assembly-CSharp-Editor.csproj'.
[dbug]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Using TargetFrameworkRootPath: /usr/local/Cellar/mono/4.8.0.524/lib/mono/xbuild-frameworks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: /Users/Sandao/Projects/Unity/AGame/Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Assembly-CSharp
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/Managed/UnityEditor.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/Managed/UnityEditor.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/Managed/UnityEngine.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/Managed/UnityEngine.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/UnityEngine.Networking.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/UnityEngine.Networking.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/PlaymodeTestsRunner/UnityEngine.PlaymodeTestsRunner.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/PlaymodeTestsRunner/UnityEngine.PlaymodeTestsRunner.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityAnalytics/UnityEngine.Analytics.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityAnalytics/UnityEngine.Analytics.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityHoloLens/RuntimeEditor/UnityEngine.HoloLens.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityHoloLens/RuntimeEditor/UnityEngine.HoloLens.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityVR/RuntimeEditor/UnityEngine.VR.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityVR/RuntimeEditor/UnityEngine.VR.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/mscorlib.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/mscorlib.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.Core.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.Core.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.Runtime.Serialization.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.Runtime.Serialization.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.XML.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.XML.dll' to 'Assembly-CSharp'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.Xml.Linq.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.Xml.Linq.dll' to 'Assembly-CSharp'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Assembly-CSharp-Editor
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/PlaybackEngines/AndroidPlayer/UnityEditor.Android.Extensions.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/PlaybackEngines/AndroidPlayer/UnityEditor.Android.Extensions.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Common.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Common.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Xcode.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Xcode.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/Managed/UnityEditor.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/Managed/UnityEditor.Graphs.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/Managed/UnityEditor.Graphs.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/Managed/UnityEngine.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/PlaybackEngines/macstandalonesupport/UnityEditor.OSXStandalone.Extensions.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/PlaybackEngines/macstandalonesupport/UnityEditor.OSXStandalone.Extensions.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Advertisements/Editor/UnityEditor.Advertisements.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Advertisements/Editor/UnityEditor.Advertisements.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/EditorTestsRunner/Editor/nunit.framework.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/EditorTestsRunner/Editor/nunit.framework.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/EditorTestsRunner/Editor/UnityEditor.EditorTestsRunner.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/EditorTestsRunner/Editor/UnityEditor.EditorTestsRunner.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/Editor/UnityEditor.UI.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/Editor/UnityEditor.UI.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/Editor/UnityEditor.Networking.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/Editor/UnityEditor.Networking.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/UnityEngine.Networking.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/PlaymodeTestsRunner/Editor/UnityEditor.PlaymodeTestsRunner.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/PlaymodeTestsRunner/Editor/UnityEditor.PlaymodeTestsRunner.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/PlaymodeTestsRunner/UnityEngine.PlaymodeTestsRunner.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/TreeEditor/Editor/UnityEditor.TreeEditor.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/TreeEditor/Editor/UnityEditor.TreeEditor.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityAnalytics/Editor/UnityEditor.Analytics.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityAnalytics/Editor/UnityEditor.Analytics.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityAnalytics/UnityEngine.Analytics.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityHoloLens/Editor/UnityEditor.HoloLens.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityHoloLens/Editor/UnityEditor.HoloLens.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityHoloLens/RuntimeEditor/UnityEngine.HoloLens.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.Services.MetadataFileReferenceCache
        Cache miss /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityVR/Editor/UnityEditor.VR.dll
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityVR/Editor/UnityEditor.VR.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityVR/RuntimeEditor/UnityEngine.VR.dll' to 'Assembly-CSharp-Editor'.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Unable to resolve assembly '/Users/Sandao/Projects/Unity/AGame/Temp/bin/Debug/Assembly-CSharp.dll'
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/mscorlib.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.Core.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.Runtime.Serialization.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.XML.dll' to 'Assembly-CSharp-Editor'.
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        Adding reference '/usr/local/Cellar/mono/4.8.0.524/lib/mono/2.0-api/System.Xml.Linq.dll' to 'Assembly-CSharp-Editor'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/Sandao/Projects/Unity/AGame'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Configuration finished.

**Comment by DustinCampbell** [comment] 2017-04-10 03:19
Ah, OK. So, the problem is specifically with the Emacs verison?

**Comment by sandao** [comment] 2017-04-10 07:13
@DustinCampbell yes！I use spacemacs！

**Comment by DustinCampbell** [comment] 2017-04-11 14:34
It sounds to me like the Emacs host might not be using the latest omnisharp-roslyn? We had a problem with locating Mono on zsh awhile back but that was fixed in early February: https://github.com/OmniSharp/omnisharp-roslyn/pull/756.

**Comment by sandao** [comment] 2017-04-12 04:33
@DustinCampbell 
I set Emacs to use the latest omnisharp-roslyn.
I added some logs and did some tests, I found the problem is Type.GetType("Mono.Runtime")  not work on my mac os,It return false.I set isMono to true like this : private static Lazy<bool> _isMono = new Lazy<bool>(() => true), and rebuild, it works fine.

**Comment by DustinCampbell** [comment] 2017-04-12 04:48
ah... yes, that should only return true if omnisharp-roslyn is actually running on Mono. If you run one of the platform-specific standalone omnisharp-roslyn builds (which run on .NET Core), the MSBuild support is somewhat limited. The .NET Core versions can only get so far with non-.NET Core MSBuild projects (like Unity) because they tend to run MSBuild tasks that are intended to run on Mono or desktop .NET Framework. Note that the Homebrew for omnisharp-roslyn has been updated to include an omnisharp-mono formula (https://github.com/OmniSharp/homebrew-omnisharp-roslyn/issues/3) to make it easier to get the Mono build.

We'll eventually be dropping the .NET Core standalone versions of OmniSharp in favor including an embedded version of Mono with OmniSharp so that everything can be self-contained and MSBuild will work as well as we can make it (https://github.com/OmniSharp/omnisharp-roslyn/issues/666).

**Comment by sandao** [comment] 2017-04-12 06:15
@DustinCampbell ok,thank you!

**Comment by razzmatazz** [comment] 2017-08-03 18:45
@sandao @DustinCampbell omnisharp-emacs now has semi-auto server installation procedure built in and it selects the proper tarball/zip file for the platform. So there should not be any need to muck with server setup manually.

I would suggest this can be closed unless @sandao still has problems with the latest version of omnisharp-emacs

**Comment by DustinCampbell** [comment] 2017-08-09 13:41
OK. I'll got ahead and close this here. @sandao, let us know if there is anymore trouble.

@razzmatazz: Note that we've made several changes to the way that omnisharp-roslyn is deployed. Hopefully, this will be easier for you now. Let me know if you have any questions.

**Closed by DustinCampbell** 2017-08-09 13:41 UTC
