### ISSUE TITLE
Build is broken on Ubuntu 20.04

### ISSUE THREAD

**Issue by Eranikid** [OmniSharp/omnisharp-roslyn#2014] opened 2020-11-12 12:37 UTC
## Expected Behavior
When I execute `$ ./build.sh`, the solution should successfully build.

## Current Behavior
Instead, I get an error saying
```
One or more errors occurred. (GitVersion: Process returned an error (exit code 1).)
```

If I execute `$ ./build.sh -v Diagnostic`, I see that error occurs due to inner exception
```
System.TypeInitializationException:
  The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
  ---> System.DllNotFoundException: lib/linux-x64/libgit2-572e4d8.so
```
Even though file `./tools/GitVersion.CommandLine.5.0.1/tools/lib/linux-x64/libgit2-572e4d8.so` exists

## Steps to Reproduce
1. `$ docker run -it ubuntu:20.04 /bin/bash`
2. `# apt update && apt install gnupg ca-certificates git curl`
3. `# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF`
4. `# echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list`
5. `# apt update && apt install mono-devel`
6. `# git clone https://github.com/OmniSharp/omnisharp-roslyn.git && cd omnisharp-roslyn`
7. `# ./build.sh`

## Workaround
I managed to get past this error by installing `libgit2-dev` package, and then symlinking `./tools/GitVersion.CommandLine.5.0.1/tools/lib/linux-x64/libgit2-572e4d8.so` to `/usr/lib/x86_64-linux-gnu/libgit2.so`

## Environment
Ubuntu 20.04
Revision 7ac4235a64fd35d2a25ce14be6d2eb5d1f266bb4

**Comment by filipw** [comment] 2020-11-12 12:45
thanks, this is a duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1891
the currently used version of GitVersion doesn't work on Unix. Another workaround is to skip running git version on local builds.

**Closed by filipw** 2020-11-12 12:45 UTC

**Comment by Eranikid** [comment] 2020-11-12 17:20
Sorry for the duplicate.
