### ISSUE TITLE
Mint Linux unable to build

### ISSUE THREAD

**Issue by zacherybohon** [OmniSharp/omnisharp-roslyn#672] opened 2016-11-21 21:54 UTC
Whenever I attempt to run the build script I get  this very succinct error message. I am guessing I have forgotten to install something along the way. 
```
./build.sh 
Feeds used:
  /home/zac/.local/share/NuGet/Cache
  /home/zac/.nuget/packages/
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

All packages listed in /home/zac/Documents/omnisharp-roslyn/scripts/packages.config are already installed.
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...

========================================
Cleanup
========================================
Executing task: Cleanup
Finished executing task: Cleanup

========================================
BuildEnvironment
========================================
Executing task: BuildEnvironment
An error occured when executing task 'BuildEnvironment'.
Error: An exception occurred during a WebClient request.
```
```
mono --version
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 14 12:30:00 UTC 2016)
```
```
dotnet --version
1.0.0-preview2-003131
```

**Comment by DustinCampbell** [comment] 2016-11-22 17:48
The problem is that the script used to obtain the .NET CLI is not smart enough to recognize Linux Mint 18: https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/scripts/obtain/dotnet-install.sh#L59-L100.

**Comment by filipw** [comment] 2021-12-06 10:30
Closing this as out of date, the build has changed much since then. If you still experience issues with the current build, please open a new issue. Thanks!

**Closed by filipw** 2021-12-06 10:30 UTC
