### ISSUE TITLE
Double clicking build errors doesn't work

### ISSUE THREAD

**Issue by rchande** [OmniSharp/omnisharp-roslyn#995] opened 2017-10-26 16:08 UTC
Create a new console app with `dotnet new`.
Open the folder in Code.
When prompted, generate the launch.json.
Add an unused variable inside main `object z;`
F5 the project.
A warning that the variable is unused appears.
Double click it.
Get an error: `Unable to open 'Program.cs': File not found (file:///Program.cs).`

**Comment by rchande** [comment] 2017-10-26 16:08
[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]

Version 1.18.0-insider
Commit e29c517386fe6f3a40e2f0ff00effae4919406aa
Date 2017-10-09T05:26:14.557Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

[OK]

**Comment by DustinCampbell** [comment] 2017-10-26 16:14
C# for VS Code bugs should be filed in omnisharp-vscode, not omnisharp-roslyn.

Also, this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1197.

**Closed by DustinCampbell** 2017-10-26 16:14 UTC
Labels: duplicate
