### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by fuzunspm** [OmniSharp/omnisharp-roslyn#1880] opened 2020-08-10 21:28 UTC
I'm on arch linux and macOS, both producing the same error during ./build.sh

> Error: One or more errors occurred. (GitVersion: Process returned an error (exit code 1).)
> 	GitVersion: Process returned an error (exit code 1).

**Comment by filipw** [comment] 2020-08-17 14:59
duplicate of #1891

**Closed by filipw** 2020-08-17 14:59 UTC
