### ISSUE TITLE
Razor intellisense

### ISSUE THREAD

**Issue by uxsoft** [OmniSharp/omnisharp-roslyn#981] opened 2017-10-17 20:14 UTC
ASP.NET/ASP.NET Core projects aren't usable using omnisharp without Razor support

**Comment by rchande** [comment] 2017-10-18 15:56
This is a known defect. See https://github.com/OmniSharp/omnisharp-vscode/issues/168 for further discussion.

**Comment by david-driscoll** [comment] 2017-10-19 19:14
This is definitely on the list to do, sadly it is something that would take some dedicated work to make it function as expected.

**Comment by Lepike** [comment] 2017-11-01 17:52
Is there any scheduled work to do this? 
It should be prioritized to gain more developers to .net core.

**Comment by DustinCampbell** [comment] 2017-11-01 18:22
@Lepike : Thanks for the prioritization feedback. I agree that this should be higher priority, but there are a lot of other issues on the backlog as well.

Note that this is an open source project that is primarily community-driven. A lot of the work happens in the spare time of volunteers. If you'd like to pitch in and help make this feature a reality, that'd be fantastic!

**Comment by mikes-gh** [comment] 2017-11-27 11:12
@DustinCampbell Microsoft will have the inside track on this.  They can look at the Visual Studio source code and see how this is currently achieved.  The community would at least need a basic plan/methodology on the best way of implementing something in vscode if you want contributions.

**Comment by PeterWone** [comment] 2017-12-14 23:56
How often does a page need comprehensive tidying? Not very. What stops you from using Visual Studio Community Edition for the occasional tidy-up? If the answer is "I don't use Windows" then I say you make your own choices and you live with the consequences.

**Comment by mikes-gh** [comment] 2017-12-15 08:42
@PeterWone This post is about insistence not formatting.

**Comment by DamianEdwards** [comment] 2018-11-02 00:17
Pretty sure this is a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/168

As noted there, support this is now available in the latest C# Extension for VS Code.

**Comment by akshita31** [comment] 2018-11-02 07:55
In the latest release of the C# extension(v 1.17), we shipped a preview Razor support. Please try it out and let us know any feedback. cc @NTaylorMullen @danroth27

**Comment by rchande** [comment] 2018-11-02 17:13
@uxsoft The asp.net team has started making progress on this feature and we have shipped a preliminary version of it. Feel free to follow along and file issues with Razor support at their repository: https://github.com/aspnet/Razor.VSCode.

**Closed by rchande** 2018-11-02 17:13 UTC

**Comment by DustinCampbell** [comment] 2018-11-06 17:56
Note that the Razor IntelliSense solution is VS Code-only. I hope this works for you @uxsoft.
