### ISSUE TITLE
VSCode /w .NET Core   IntelliSense is not working

### ISSUE THREAD

**Issue by GrimR3** [OmniSharp/omnisharp-roslyn#375] opened 2016-01-06 17:06 UTC
omnisharp  in VSCode is not finding the correct directory for .Net Core which puts everything in `\.dnx\packages\`

I installed .NetCore for Windows from http://dotnet.github.io/getting-started/
`(https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-win-x64.latest.msi)`

ran the following commands
````
dotnet new
dotnet restore
````
Opened the folder in VS Code and got the following error.

    Some projects have trouble loading. Please review the output for more details.

**Output:**
````
INFO] Starting OmniSharp at 'c:\Users\USER\Projects'...
[INFO] Started OmniSharp from 'c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\bin\omnisharp.cmd' with process id 6480...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location 'c:\Users\USER\Projects' on host 1708.
[ERROR:OmniSharp.Dnx.DnxPaths] The specified runtime path 'default' does not exist. Searched locations C:\Users\USER\.dnx\runtimes\dnx-clr-win-x86.default
C:\Users\USER\.dnx\runtimes\kre-clr-win-x86.default
C:\Users\USER\.dnx\packages\KRE-CLR-x86.default
C:\Users\USER\.k\runtimes\dnx-clr-win-x86.default
C:\Users\USER\.k\runtimes\kre-clr-win-x86.default
C:\Users\USER\.k\packages\KRE-CLR-x86.default
C:\Users\USER\.kre\runtimes\dnx-clr-win-x86.default
C:\Users\USER\.kre\runtimes\kre-clr-win-x86.default
C:\Users\USER\.kre\packages\KRE-CLR-x86.default.
Visit https://github.com/aspnet/Home for an installation guide.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning 'c:\Users\USER\Projects' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project 'c:\Users\USER\Projects\project.json'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] No default runtime found
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading
The specified runtime path 'default' does not exist. Searched locations C:\Users\USER\.dnx\runtimes\dnx-clr-win-x86.default
C:\Users\USER\.dnx\runtimes\kre-clr-win-x86.default
C:\Users\USER\.dnx\packages\KRE-CLR-x86.default
C:\Users\USER\.k\runtimes\dnx-clr-win-x86.default
C:\Users\USER\.k\runtimes\kre-clr-win-x86.default
C:\Users\USER\.k\packages\KRE-CLR-x86.default
C:\Users\USER\.kre\runtimes\dnx-clr-win-x86.default
C:\Users\USER\.kre\runtimes\kre-clr-win-x86.default
C:\Users\USER\.kre\packages\KRE-CLR-x86.default.
Visit https://github.com/aspnet/Home for an installation guide.

[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in 'c:\Users\USER\Projects'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in 'c:\Users\USER\Projects'
````

**Comment by david-driscoll** [comment] 2016-01-21 03:13
Support for the latest dotnet-cli is coming soon, in some cases it might not work in other cases it might.

**Comment by nathanielcook** [comment] 2016-02-08 19:36
@david-driscoll if I'm not mistaken, this doesn't have to do with the dotnet-cli. Is this not another manifestation of this issue: OmniSharp/omnisharp-vscode#12 If so, then there is a pull request out there for that: https://github.com/OmniSharp/omnisharp-roslyn/pull/397 I for example and hitting this error and I haven't upgraded to the dotnet cli yet.

**Comment by nathanielcook** [comment] 2016-02-08 19:41
Might also be a duplicate of this issue: https://github.com/OmniSharp/omnisharp-roslyn/issues/375

**Comment by troydai** [comment] 2016-03-17 23:25
The __dotnet-cli__ support is ready on [dev](https://github.com/OmniSharp/omnisharp-roslyn/tree/dev) branch. Please try out [v1.9-alpha3 release](https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.9-alpha3), and [__VS Code__ instruction](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/README.md).

**Closed by troydai** 2016-03-17 23:25 UTC

**Comment by developerTN** [comment] 2017-06-16 16:48
Hi,
Could you point to me how to fix the problem using the release ? I just found on the downloaded release a bunch of dlls, do I have to paste them somewhere ?

thanks
