### ISSUE TITLE
Building error: GitVersion failed. Setting default version 0.0.1-local

### ISSUE THREAD

**Issue by Exoskeleton1111111111** [OmniSharp/omnisharp-roslyn#2067] opened 2021-01-21 05:06 UTC
So I go onto VS Code and run the build script ```./build.ps1 ``` so it prepares to run script and runs script but after that it gives me the error 'GitVersion failed. Setting default version 0.0.1-local', I have git and mono installed, but it still comes, also on a fresh install of Omnisharp Roslyn. And it gives me some other errors after that.

build.ps1 log:
```
Preparing to run build script...
Running build script...
GitVersion failed. Setting default version 0.0.1-local

Current platform: Windows 6.2.9200.0 (x64)


========================================
Cleanup
========================================

========================================
InstallDotNetCoreSdk
========================================
An error occurred when executing task 'InstallDotNetCoreSdk'.

----------------------------------------
Teardown
----------------------------------------
An error occurred in a custom teardown action.
Teardown error: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Submission#0.Run(String command, String arguments, RunOptions runOptions) in C:\Users\Asus\Downloads\GitDownloads\omnisharp-roslyn-master\scripts\runhelpers.cake:line 153
   at Submission#0.Run(String command, String arguments) in C:\Users\Asus\Downloads\GitDownloads\omnisharp-roslyn-master\scripts\runhelpers.cake:line 107
   at Submission#0.<<Initialize>>b__0_21(ITeardownContext context) in C:\Users\Asus\Downloads\GitDownloads\omnisharp-roslyn-master\build.cake:line 960  
   at Cake.Core.DefaultExecutionStrategy.PerformTeardown(Action`1 action, ITeardownContext teardownContext)
   at Cake.Core.CakeEngine.PerformTeardown(IExecutionStrategy strategy, ICakeContext context, Stopwatch stopWatch, CakeReport report, Boolean exceptionWasThrown, Exception thrownException)
Error: One or more errors occurred.
        The remote name could not be resolved: 'dot.net'
```

**Comment by filipw** [comment] 2021-01-22 06:58
Please provide the full log. version `0.0.1-local'` is just a dummy one used for local builds

**Comment by filipw** [comment] 2021-01-25 07:58
the problem is the space in your folder name, this is currently not supported, try again from a folder without space

**Comment by Exoskeleton1111111111** [comment] 2021-01-26 11:59
> the problem is the space in your folder name, this is currently not supported, try again from a folder without space

It still didnt work, i updated the log just now.

**Comment by filipw** [comment] 2021-01-26 12:43
> The remote name could not be resolved: 'dot.net'

are you online? looks like your DNS isn't working

**Comment by filipw** [comment] 2021-03-10 20:55
> The remote name could not be resolved: 'dot.net'

closing as this is not a OmniSharp issue, but rather a local one

**Closed by filipw** 2021-03-10 20:55 UTC
Labels: build
