### ISSUE TITLE
String interpolation confounds text coloring

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-roslyn#588] opened 2016-06-20 19:31 UTC
_From @BRS999 on June 18, 2016 12:39_
- VSCode Version: 1.2.1
- OS Version:  OSX 10.11.5

Background: I was playing around with some new C# features when I noticed the text coloration became wonky in VSCode.

Steps to Reproduce:
1. Add this line of code to a blank cs file `public void Print() => WriteLine($"Your name is {FirstName} and {LastName}");`
2. Add this line of code after it `public void sqrt() => WriteLine(Sqrt(3 * 3 + 4 + 4));`
3. Observe the wonky text coloring.

See screenshot
<img width="727" alt="screen shot 2016-06-18 at 8 37 53 am" src="https://cloud.githubusercontent.com/assets/6516437/16170902/f7852818-352f-11e6-9e60-eb8024c2f141.png">

_Copied from original issue: Microsoft/vscode#7849_

**Comment by david-driscoll** [comment] 2016-06-20 19:55
@jrieken this should probably goto the omnisharp-vscode repo, as it appears to be an issue with the textmate grammer.  (colorization in vscode doesn't use roslyn today)

**Comment by willl** [comment] 2016-06-21 01:59
As @david-driscoll said. And there seems to be several [similar issues already reported](https://github.com/OmniSharp/omnisharp-vscode/search?utf8=%E2%9C%93&q=string+interpolation&type=Issues).

Probably close'ish related to https://github.com/OmniSharp/omnisharp-vscode/issues/347.

And it was mentioned [here](https://github.com/OmniSharp/OmniSharp/issues/12#issuecomment-219503392): `Better Syntax Highlighting - Need API from VS Code to allow extension to do more than just provide TextMate grammar`.

**Comment by DustinCampbell** [comment] 2016-06-23 17:41
@jrieken -- could you be sure to file VS Code issues to the omnisharp-vscode repo instead of omnisharp-roslyn?

**Comment by DustinCampbell** [comment] 2016-11-02 13:41
This looks like a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/679.

**Closed by DustinCampbell** 2016-11-02 13:41 UTC
Labels: duplicate
