### ISSUE TITLE
Invalid character in group name

### ISSUE THREAD

**Issue by Wjinlei** [OmniSharp/omnisharp-roslyn#2484] opened 2022-12-14 03:10 UTC
I installed OmniSharp using neovim and `nvim-lsp-installer`. When I opened the `cs` file, I got the following error

![error](https://user-images.githubusercontent.com/11342964/207495800-8047a468-6763-4455-b311-53d4a2636a3e.png)

I don't know what the problem is, please help me

**Comment by shaksiper** [comment] 2022-12-15 01:40
See #2483 
I don't think this is a major problem, it's just that the maintainers need to look into it I think.

**Comment by filipw** [comment] 2023-01-12 08:58
I will close this as duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/2483

**Closed by filipw** 2023-01-12 08:58 UTC
