### ISSUE TITLE
Support for .csproj file code assistance

### ISSUE THREAD

**Issue by mickaelistria** [OmniSharp/omnisharp-roslyn#1080] opened 2018-01-10 08:39 UTC
It would be nice if OmniSharp could also provide coding assistance for .csproj files. It seems like some results are already available at https://github.com/tintoy/msbuild-project-tools-vscode . As an embedder of such tools to create a C# extension to some IDEs, I have the feeling it would make a lot of sense to try to merge the .csproj support into OmniSharp.
However, I admit I know too little about both codebases to know how doable it is.
cc @tintoy

**Comment by tintoy** [comment] 2018-01-10 11:25
Hi :)

Looked into this a while back, but got side-tracked; the code-bases are pretty different so I think the last time it was discussed the idea was to make an extension pack that bundled omnisharp with msbuild project tools, cake, and possibly others too. I'm not against the idea of merging it into omnisharp per se but I think the way it's built currently there isn't really a good place in their API surface to expose it. I guess I don't have a strong opinion either way but I *would* like to make it as convenient as possible for both users and consumers.

CC: @david-driscoll @DustinCampbell

**Comment by filipw** [comment] 2020-11-26 14:54
duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/951

**Closed by filipw** 2020-11-26 14:54 UTC
Labels: feature request
