### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Dimbel1** [OmniSharp/omnisharp-roslyn#620] opened 2016-08-13 14:13 UTC
Hey guys, i cant build omnisharp roslyn. I cloned the project and checked out, but when i want to build it, i got 2 errors:
./build.ps1: line 1: :OMNISHARP_PACKAGE_OSNAME: command not found
./build.ps1: line 2: .scriptscake-bootstrap.ps1: command not found

Do i miss some prerequisites?

**Comment by willl** [comment] 2016-08-14 06:17
@Dimbel1: Could you please provide additional details like what OS you are running?

And what are you using to run the build?

**Comment by DustinCampbell** [comment] 2016-09-17 22:13
This is a month old. @Dimbel1, are you OK if we go ahead and close this?

**Comment by jayvachon** [comment] 2016-09-22 13:42
I'm also getting this on Windows 10

**Comment by DustinCampbell** [comment] 2016-09-22 14:28
A couple of questions:

* Are you running this within a normal Windows Command Prompt (elevated or otherwise)?
* Do you have PowerShell configured to run scripts (e.g. `set-executionpolicy Unrestricted`)?

**Comment by jayvachon** [comment] 2016-09-22 14:51
Originally tried this using Command Prompt, but tried it in PowerShell running as admin and got this:
```
Could not find Cake.exe at C:\Program Files\omnisharp-roslyn\scripts\..\.tools\Cake\Cake.exe
At C:\Program Files\omnisharp-roslyn\scripts\cake-bootstrap.ps1:113 char:5
+     Throw "Could not find Cake.exe at $CAKE_EXE"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...s\Cake\Cake.exe:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Cake.exe at C:\Program Files\omnisharp-roslyn\scripts\..\.tools\Cake\Cake
   .exe
```
(looks related to https://github.com/OmniSharp/omnisharp-roslyn/issues/484)

**Comment by DustinCampbell** [comment] 2016-11-02 10:19
FWIW, it *does* look similar to #484, but that issue seems to have been solved.

**Comment by DustinCampbell** [comment] 2016-11-02 10:21
@david-driscoll, do you have any ideas?

**Comment by DustinCampbell** [comment] 2017-05-03 23:34
OK. I see what's happening. The problem is the space in the path name (e.g. `C:\Program Files\omnisharp-roslyn\scripts.....`). We're tracking this problem with #691.

**Closed by DustinCampbell** 2017-05-03 23:34 UTC
Labels: infrastructure
